import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart6 = {
  'continental': {
    'breakfast': [
      CategoryDish(id: 'c-co-b1', name: 'Pancakes with Honey', description: 'Fluffy pancakes with honey drizzle.', timeMinutes: 20),
      CategoryDish(id: 'c-co-b2', name: 'Avocado Toast', description: 'Toast with smashed avocado and pepper.', timeMinutes: 10),
      CategoryDish(id: 'c-co-b3', name: 'Baked Beans on Toast', description: 'Hearty beans over golden toast.', timeMinutes: 15),
      CategoryDish(id: 'c-co-b4', name: 'French Toast', description: 'Egg-dipped bread, crisp and sweet.', timeMinutes: 15),
      CategoryDish(id: 'c-co-b5', name: 'Muesli Bowl', description: 'Cereal with yogurt and fruit.', timeMinutes: 10),
    ],
    'healthy': [
      CategoryDish(id: 'c-co-h1', name: 'Grilled Chicken Salad', description: 'Chicken over crisp greens.', timeMinutes: 25),
      CategoryDish(id: 'c-co-h2', name: 'Oats Bowl', description: 'Warm oats with nuts and berries.', timeMinutes: 15),
      CategoryDish(id: 'c-co-h3', name: 'Quinoa Salad', description: 'Protein-rich salad with vegetables.', timeMinutes: 25),
      CategoryDish(id: 'c-co-h4', name: 'Steamed Veg Medley', description: 'Simple steamed seasonal vegetables.', timeMinutes: 20),
      CategoryDish(id: 'c-co-h5', name: 'Avocado Salad', description: 'Creamy avocado with lemon and herbs.', timeMinutes: 10),
    ],
    'dinner': [
      CategoryDish(id: 'c-co-d1', name: 'Grilled Steak', description: 'Pan-seared steak with herb butter.', timeMinutes: 30),
      CategoryDish(id: 'c-co-d2', name: 'Baked Salmon', description: 'Oven-baked salmon with lemon.', timeMinutes: 30),
      CategoryDish(id: 'c-co-d3', name: 'Shepherd\'s Pie', description: 'Mince pie with mashed potato top.', timeMinutes: 60),
      CategoryDish(id: 'c-co-d4', name: 'Creamy Mushroom Pasta', description: 'Pasta in a creamy mushroom sauce.', timeMinutes: 30),
      CategoryDish(id: 'c-co-d5', name: 'Roast Chicken', description: 'Simple roast chicken with vegetables.', timeMinutes: 70),
    ],
    'veg': [
      CategoryDish(id: 'c-co-v1', name: 'Creamy Mushroom Pasta', description: 'Comforting pasta with mushrooms.', timeMinutes: 30),
      CategoryDish(id: 'c-co-v2', name: 'Veg Lasagna', description: 'Baked pasta with tomato and cheese.', timeMinutes: 60),
      CategoryDish(id: 'c-co-v3', name: 'Grilled Veg Sandwich', description: 'Pesto grilled vegetables on bread.', timeMinutes: 20),
      CategoryDish(id: 'c-co-v4', name: 'Ratatouille', description: 'Slow-cooked French vegetables.', timeMinutes: 55),
      CategoryDish(id: 'c-co-v5', name: 'Potato Gratin', description: 'Creamy baked potato slices.', timeMinutes: 50),
    ],
    'nonveg': [
      CategoryDish(id: 'c-co-n1', name: 'Grilled Steak', description: 'Juicy steak with sides.', timeMinutes: 30),
      CategoryDish(id: 'c-co-n2', name: 'Baked Salmon', description: 'Simple, healthy fish bake.', timeMinutes: 30),
      CategoryDish(id: 'c-co-n3', name: 'Chicken Stew', description: 'Hearty slow-simmered stew.', timeMinutes: 50),
      CategoryDish(id: 'c-co-n4', name: 'Barbecue Ribs', description: 'Sticky, smoky glazed ribs.', timeMinutes: 90),
      CategoryDish(id: 'c-co-n5', name: 'Fish and Chips', description: 'Crisp beer-battered fish.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-co-s1', name: 'Chocolate Fondant', description: 'Warm cake with a molten centre.', timeMinutes: 35),
      CategoryDish(id: 'c-co-s2', name: 'Apple Crumble', description: 'Baked apples under a crumbly top.', timeMinutes: 50),
      CategoryDish(id: 'c-co-s3', name: 'Vanilla Pudding', description: 'Classic creamy pudding.', timeMinutes: 25),
      CategoryDish(id: 'c-co-s4', name: 'Berry Tart', description: 'Shortcrust tart with berries.', timeMinutes: 45),
      CategoryDish(id: 'c-co-s5', name: 'Bread Pudding', description: 'Baked sweet bread dessert.', timeMinutes: 50),
    ],
    'kids': [
      CategoryDish(id: 'c-co-k1', name: 'Mini Pancakes', description: 'Small sweet pancakes.', timeMinutes: 20),
      CategoryDish(id: 'c-co-k2', name: 'Mac and Cheese', description: 'Creamy cheesy pasta.', timeMinutes: 25),
      CategoryDish(id: 'c-co-k3', name: 'Chicken Nuggets', description: 'Crisp golden nuggets.', timeMinutes: 25),
      CategoryDish(id: 'c-co-k4', name: 'Cheese Quesadilla', description: 'Melted cheese in crisp tortilla.', timeMinutes: 15),
      CategoryDish(id: 'c-co-k5', name: 'Chocolate Pudding Cup', description: 'Small pot of chocolate pudding.', timeMinutes: 20),
    ],
  },
  'french': {
    'breakfast': [
      CategoryDish(id: 'c-fr-b1', name: 'Croissant', description: 'Flaky buttery pastry.', timeMinutes: 60),
      CategoryDish(id: 'c-fr-b2', name: 'Omelette aux Herbes', description: 'Soft herb omelette.', timeMinutes: 10),
      CategoryDish(id: 'c-fr-b3', name: 'Pain Perdu', description: 'French toast with a custard soak.', timeMinutes: 20),
      CategoryDish(id: 'c-fr-b4', name: 'Yogurt and Fruit', description: 'Simple morning bowl.', timeMinutes: 5),
      CategoryDish(id: 'c-fr-b5', name: 'Crepes', description: 'Thin pancakes with lemon and sugar.', timeMinutes: 25),
    ],
    'healthy': [
      CategoryDish(id: 'c-fr-h1', name: 'Nicoise Salad', description: 'Tuna, egg and olive salad.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-h2', name: 'Vichyssoise', description: 'Chilled leek and potato soup.', timeMinutes: 40),
      CategoryDish(id: 'c-fr-h3', name: 'Ratatouille', description: 'Light vegetable stew.', timeMinutes: 55),
      CategoryDish(id: 'c-fr-h4', name: 'Poached Chicken', description: 'Gently poached chicken breast.', timeMinutes: 30),
      CategoryDish(id: 'c-fr-h5', name: 'Haricots Verts', description: 'Green beans with shallots.', timeMinutes: 20),
    ],
    'dinner': [
      CategoryDish(id: 'c-fr-d1', name: 'Coq au Vin', description: 'Chicken braised in red wine.', timeMinutes: 90),
      CategoryDish(id: 'c-fr-d2', name: 'Beef Bourguignon', description: 'Rich slow-braised beef.', timeMinutes: 120),
      CategoryDish(id: 'c-fr-d3', name: 'Salmon en Papillote', description: 'Fish baked in a parchment parcel.', timeMinutes: 30),
      CategoryDish(id: 'c-fr-d4', name: 'Quiche Lorraine', description: 'Baked tart with bacon and cream.', timeMinutes: 55),
      CategoryDish(id: 'c-fr-d5', name: 'Steak Frites', description: 'Steak with crisp fries.', timeMinutes: 30),
    ],
    'veg': [
      CategoryDish(id: 'c-fr-v1', name: 'Ratatouille', description: 'Provencal vegetable stew.', timeMinutes: 55),
      CategoryDish(id: 'c-fr-v2', name: 'Quiche aux Legumes', description: 'Vegetable quiche.', timeMinutes: 55),
      CategoryDish(id: 'c-fr-v3', name: 'Soupe a l\'Oignon', description: 'French onion soup with cheese toast.', timeMinutes: 60),
      CategoryDish(id: 'c-fr-v4', name: 'Gratin Dauphinois', description: 'Creamy baked potato gratin.', timeMinutes: 60),
      CategoryDish(id: 'c-fr-v5', name: 'Salade Lyonnaise', description: 'Green salad with a warm egg.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-fr-n1', name: 'Coq au Vin', description: 'Wine-braised chicken classic.', timeMinutes: 90),
      CategoryDish(id: 'c-fr-n2', name: 'Duck Confit', description: 'Slow-cooked crisp duck.', timeMinutes: 120),
      CategoryDish(id: 'c-fr-n3', name: 'Moules Mariniere', description: 'Mussels in garlic white wine.', timeMinutes: 30),
      CategoryDish(id: 'c-fr-n4', name: 'Steak au Poivre', description: 'Pepper-crusted steak.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-n5', name: 'Salmon Rillettes', description: 'Spreadable smoked salmon.', timeMinutes: 25),
    ],
    'sweet': [
      CategoryDish(id: 'c-fr-s1', name: 'Crème Brûlée', description: 'Silky custard with a caramel crust.', timeMinutes: 40),
      CategoryDish(id: 'c-fr-s2', name: 'Chocolate Mousse', description: 'Light and airy dark chocolate.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-s3', name: 'Tarte Tatin', description: 'Upside-down caramelised apple tart.', timeMinutes: 55),
      CategoryDish(id: 'c-fr-s4', name: 'Macarons', description: 'Delicate almond cookies.', timeMinutes: 60),
      CategoryDish(id: 'c-fr-s5', name: 'Crêpes Suzette', description: 'Orange butter flamed crepes.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-fr-k1', name: 'Crepe Roll', description: 'Sweet crepe rolled with jam.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-k2', name: 'Ham and Cheese Croissant', description: 'Warm stuffed pastry.', timeMinutes: 15),
      CategoryDish(id: 'c-fr-k3', name: 'French Fries', description: 'Crisp golden fries.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-k4', name: 'Chocolate Mousse Cup', description: 'Small chocolate pot.', timeMinutes: 25),
      CategoryDish(id: 'c-fr-k5', name: 'Petit Crepes', description: 'Mini pancakes for little hands.', timeMinutes: 25),
    ],
  },
  'mexican': {
    'breakfast': [
      CategoryDish(id: 'c-mx-b1', name: 'Huevos Rancheros', description: 'Fried eggs on tortillas with salsa.', timeMinutes: 25),
      CategoryDish(id: 'c-mx-b2', name: 'Chilaquiles', description: 'Crisp tortillas in salsa, topped with egg.', timeMinutes: 25),
      CategoryDish(id: 'c-mx-b3', name: 'Breakfast Burrito', description: 'Tortilla with eggs, beans and cheese.', timeMinutes: 20),
      CategoryDish(id: 'c-mx-b4', name: 'Mexican Omelette', description: 'Omelette with peppers and salsa.', timeMinutes: 15),
      CategoryDish(id: 'c-mx-b5', name: 'Corn and Cheese Empanada', description: 'Savory stuffed pastry.', timeMinutes: 35),
    ],
    'healthy': [
      CategoryDish(id: 'c-mx-h1', name: 'Fresh Salsa Salad', description: 'Tomato, onion and avocado salad.', timeMinutes: 15),
      CategoryDish(id: 'c-mx-h2', name: 'Black Bean Bowl', description: 'Beans with rice, corn and salsa.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-h3', name: 'Chicken Fajita Bowl', description: 'Grilled chicken with veggies.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-h4', name: 'Mexican Corn Salad', description: 'Elote-style corn salad.', timeMinutes: 20),
      CategoryDish(id: 'c-mx-h5', name: 'Zucchini Tacos', description: 'Light tacos with grilled zucchini.', timeMinutes: 25),
    ],
    'dinner': [
      CategoryDish(id: 'c-mx-d1', name: 'Chicken Enchiladas', description: 'Rolled tortillas in chilli sauce.', timeMinutes: 50),
      CategoryDish(id: 'c-mx-d2', name: 'Beef Tacos', description: 'Crisp tacos with spiced beef.', timeMinutes: 35),
      CategoryDish(id: 'c-mx-d3', name: 'Burrito Bowl', description: 'Rice, beans, salsa and protein.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-d4', name: 'Chili con Carne', description: 'Spiced beef and bean stew.', timeMinutes: 50),
      CategoryDish(id: 'c-mx-d5', name: 'Cheese Quesadillas', description: 'Golden tortillas with melted cheese.', timeMinutes: 20),
    ],
    'veg': [
      CategoryDish(id: 'c-mx-v1', name: 'Veggie Burrito', description: 'Beans and veg in a tortilla.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-v2', name: 'Cheese Quesadilla', description: 'Simple and melty.', timeMinutes: 20),
      CategoryDish(id: 'c-mx-v3', name: 'Veg Enchiladas', description: 'Vegetable enchiladas in salsa.', timeMinutes: 45),
      CategoryDish(id: 'c-mx-v4', name: 'Bean Tacos', description: 'Refried bean tacos with salsa.', timeMinutes: 25),
      CategoryDish(id: 'c-mx-v5', name: 'Elote', description: 'Mexican street corn with lime.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-mx-n1', name: 'Beef Tacos', description: 'Classic street-style tacos.', timeMinutes: 35),
      CategoryDish(id: 'c-mx-n2', name: 'Chicken Fajitas', description: 'Sizzling chicken with peppers.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-n3', name: 'Carnitas', description: 'Slow-cooked pulled pork.', timeMinutes: 120),
      CategoryDish(id: 'c-mx-n4', name: 'Chili con Carne', description: 'Spiced meat and bean chili.', timeMinutes: 50),
      CategoryDish(id: 'c-mx-n5', name: 'Fish Tacos', description: 'Crisp fish with slaw.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-mx-s1', name: 'Churros', description: 'Cinnamon-sugar fried dough.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-s2', name: 'Flan', description: 'Silky caramel custard.', timeMinutes: 50),
      CategoryDish(id: 'c-mx-s3', name: 'Tres Leches Cake', description: 'Milk-soaked sponge cake.', timeMinutes: 50),
      CategoryDish(id: 'c-mx-s4', name: 'Arroz con Leche', description: 'Creamy rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-mx-s5', name: 'Mexican Hot Chocolate', description: 'Warm spiced chocolate drink.', timeMinutes: 15),
    ],
    'kids': [
      CategoryDish(id: 'c-mx-k1', name: 'Cheese Quesadilla', description: 'Melty cheese wedges.', timeMinutes: 15),
      CategoryDish(id: 'c-mx-k2', name: 'Mini Tacos', description: 'Small soft tacos.', timeMinutes: 25),
      CategoryDish(id: 'c-mx-k3', name: 'Churro Bites', description: 'Sweet cinnamon sticks.', timeMinutes: 30),
      CategoryDish(id: 'c-mx-k4', name: 'Corn Cup', description: 'Sweet corn with cheese.', timeMinutes: 15),
      CategoryDish(id: 'c-mx-k5', name: 'Burrito Roll', description: 'Simple bean roll-ups.', timeMinutes: 20),
    ],
  },
  'mediterranean': {
    'breakfast': [
      CategoryDish(id: 'c-md-b1', name: 'Shakshuka', description: 'Eggs poached in tomato-pepper sauce.', timeMinutes: 30),
      CategoryDish(id: 'c-md-b2', name: 'Greek Yogurt Bowl', description: 'Yogurt with honey and nuts.', timeMinutes: 10),
      CategoryDish(id: 'c-md-b3', name: 'Feta and Olive Toast', description: 'Toast with feta and olives.', timeMinutes: 10),
      CategoryDish(id: 'c-md-b4', name: 'Hummus and Pita', description: 'Creamy hummus with warm pita.', timeMinutes: 20),
      CategoryDish(id: 'c-md-b5', name: 'Mediterranean Omelette', description: 'Omelette with spinach and feta.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-md-h1', name: 'Greek Salad', description: 'Tomato, cucumber, olives and feta.', timeMinutes: 15),
      CategoryDish(id: 'c-md-h2', name: 'Tabbouleh', description: 'Bulgur salad with parsley and lemon.', timeMinutes: 25),
      CategoryDish(id: 'c-md-h3', name: 'Grilled Fish Mediterranean', description: 'Fish with lemon and oregano.', timeMinutes: 25),
      CategoryDish(id: 'c-md-h4', name: 'Fattoush', description: 'Bread salad with sumac.', timeMinutes: 20),
      CategoryDish(id: 'c-md-h5', name: 'Chickpea Salad', description: 'Herby chickpea salad.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-md-d1', name: 'Grilled Chicken Souvlaki', description: 'Marinated skewers with pita.', timeMinutes: 35),
      CategoryDish(id: 'c-md-d2', name: 'Moussaka', description: 'Baked eggplant and meat bake.', timeMinutes: 75),
      CategoryDish(id: 'c-md-d3', name: 'Seafood Paella', description: 'Saffron rice with seafood.', timeMinutes: 50),
      CategoryDish(id: 'c-md-d4', name: 'Lamb Kofta', description: 'Spiced lamb skewers.', timeMinutes: 40),
      CategoryDish(id: 'c-md-d5', name: 'Stuffed Peppers', description: 'Peppers filled with rice and herbs.', timeMinutes: 55),
    ],
    'veg': [
      CategoryDish(id: 'c-md-v1', name: 'Falafel Wrap', description: 'Crisp chickpea patties in pita.', timeMinutes: 40),
      CategoryDish(id: 'c-md-v2', name: 'Stuffed Grape Leaves', description: 'Vine leaves with herbed rice.', timeMinutes: 60),
      CategoryDish(id: 'c-md-v3', name: 'Roasted Vegetables', description: 'Mediterranean roasted veg.', timeMinutes: 40),
      CategoryDish(id: 'c-md-v4', name: 'Spinach and Feta Pie', description: 'Crisp pastry with spinach filling.', timeMinutes: 50),
      CategoryDish(id: 'c-md-v5', name: 'Hummus Bowl', description: 'Hummus with veg sticks and pita.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-md-n1', name: 'Chicken Souvlaki', description: 'Grilled chicken skewers.', timeMinutes: 35),
      CategoryDish(id: 'c-md-n2', name: 'Lamb Kofta', description: 'Herby lamb skewers.', timeMinutes: 40),
      CategoryDish(id: 'c-md-n3', name: 'Shrimp Saganaki', description: 'Prawns in tomato-feta sauce.', timeMinutes: 25),
      CategoryDish(id: 'c-md-n4', name: 'Seafood Paella', description: 'Saffron rice with the catch of the day.', timeMinutes: 50),
      CategoryDish(id: 'c-md-n5', name: 'Moroccan Chicken', description: 'Chicken with olives and lemon.', timeMinutes: 55),
    ],
    'sweet': [
      CategoryDish(id: 'c-md-s1', name: 'Baklava', description: 'Layered pastry with nuts and honey.', timeMinutes: 60),
      CategoryDish(id: 'c-md-s2', name: 'Rizogalo', description: 'Greek cinnamon rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-md-s3', name: 'Kunafa', description: 'Shredded pastry with cheese and syrup.', timeMinutes: 50),
      CategoryDish(id: 'c-md-s4', name: 'Orange Cake', description: 'Moist olive-oil orange cake.', timeMinutes: 50),
      CategoryDish(id: 'c-md-s5', name: 'Bougatsa', description: 'Custard-filled pastry with sugar.', timeMinutes: 55),
    ],
    'kids': [
      CategoryDish(id: 'c-md-k1', name: 'Pita with Hummus', description: 'Soft bread with creamy dip.', timeMinutes: 10),
      CategoryDish(id: 'c-md-k2', name: 'Falafel Bites', description: 'Small crisp chickpea balls.', timeMinutes: 30),
      CategoryDish(id: 'c-md-k3', name: 'Greek Yogurt Honey Cup', description: 'Sweet yogurt snack.', timeMinutes: 5),
      CategoryDish(id: 'c-md-k4', name: 'Souvlaki Stick', description: 'Mild chicken on a skewer.', timeMinutes: 30),
      CategoryDish(id: 'c-md-k5', name: 'Baklava Bite', description: 'Small sweet pastry piece.', timeMinutes: 30),
    ],
  },
  'korean': {
    'breakfast': [
      CategoryDish(id: 'c-ko-b1', name: 'Kimchi Pancake', description: 'Savory pancake with kimchi.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-b2', name: 'Rice Soup Korean', description: 'Light rice and egg soup.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-b3', name: 'Scallion Pancake', description: 'Crisp green onion pancake.', timeMinutes: 25),
      CategoryDish(id: 'c-ko-b4', name: 'Steamed Egg Custard', description: 'Silky savoury egg bowl.', timeMinutes: 15),
      CategoryDish(id: 'c-ko-b5', name: 'Banana Milk Bowl', description: 'Sweet morning drink with rice.', timeMinutes: 10),
    ],
    'healthy': [
      CategoryDish(id: 'c-ko-h1', name: 'Bibimbap Light', description: 'Rice bowl with vegetables and egg.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-h2', name: 'Doenjang Soup', description: 'Soybean paste soup with veg.', timeMinutes: 25),
      CategoryDish(id: 'c-ko-h3', name: 'Kongnamul Salad', description: 'Sesame bean sprout salad.', timeMinutes: 15),
      CategoryDish(id: 'c-ko-h4', name: 'Japchae', description: 'Glass noodles with vegetables.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-h5', name: 'Tofu Stew Light', description: 'Soft tofu in a light broth.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-ko-d1', name: 'Bulgogi', description: 'Marinated grilled beef.', timeMinutes: 40),
      CategoryDish(id: 'c-ko-d2', name: 'Kimchi Stew', description: 'Spicy pork and kimchi stew.', timeMinutes: 40),
      CategoryDish(id: 'c-ko-d3', name: 'Korean Fried Chicken', description: 'Crisp double-fried chicken.', timeMinutes: 45),
      CategoryDish(id: 'c-ko-d4', name: 'Bibimbap', description: 'Mixed rice with gochujang.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-d5', name: 'Galbi', description: 'Grilled soy-garlic short ribs.', timeMinutes: 60),
    ],
    'veg': [
      CategoryDish(id: 'c-ko-v1', name: 'Vegetable Japchae', description: 'Sweet potato noodles with veg.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-v2', name: 'Kimchi Pancake', description: 'Savory and slightly spicy.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-v3', name: 'Tofu Bibimbap', description: 'Bowl with tofu and vegetables.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-v4', name: 'Stir-Fried Kimchi', description: 'Sautéed kimchi with tofu.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-v5', name: 'Mushroom Jeon', description: 'Crisp battered mushrooms.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ko-n1', name: 'Bulgogi', description: 'Sweet-savoury grilled beef.', timeMinutes: 40),
      CategoryDish(id: 'c-ko-n2', name: 'Korean Fried Chicken', description: 'Glazed crispy chicken.', timeMinutes: 45),
      CategoryDish(id: 'c-ko-n3', name: 'Kimchi Jjigae', description: 'Hearty pork kimchi stew.', timeMinutes: 40),
      CategoryDish(id: 'c-ko-n4', name: 'Jeyuk Bokkeum', description: 'Spicy stir-fried pork.', timeMinutes: 30),
      CategoryDish(id: 'c-ko-n5', name: 'Galbi', description: 'Sticky grilled ribs.', timeMinutes: 60),
    ],
    'sweet': [
      CategoryDish(id: 'c-ko-s1', name: 'Hotteok', description: 'Sweet filled pancakes.', timeMinutes: 30),
      CategoryDish(id: 'c-ko-s2', name: 'Songpyeon', description: 'Rice cakes filled with sesame.', timeMinutes: 60),
      CategoryDish(id: 'c-ko-s3', name: 'Bungeoppang', description: 'Fish-shaped pastry with red bean.', timeMinutes: 35),
      CategoryDish(id: 'c-ko-s4', name: 'Patbingsu', description: 'Shaved ice with toppings.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-s5', name: 'Yakgwa', description: 'Honey-fried cookies.', timeMinutes: 45),
    ],
    'kids': [
      CategoryDish(id: 'c-ko-k1', name: 'Kimbap Roll', description: 'Rice roll with veggies.', timeMinutes: 40),
      CategoryDish(id: 'c-ko-k2', name: 'Hotteok Bite', description: 'Warm sweet pancake.', timeMinutes: 30),
      CategoryDish(id: 'c-ko-k3', name: 'Mini Kimchi Pancake', description: 'Small mild pancake.', timeMinutes: 20),
      CategoryDish(id: 'c-ko-k4', name: 'Egg Rice Bowl', description: 'Rice with a soft egg.', timeMinutes: 10),
      CategoryDish(id: 'c-ko-k5', name: 'Banana Milk', description: 'Sweet banana drink.', timeMinutes: 5),
    ],
  },
};
