import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart3 = {
  'maharashtrian': {
    'breakfast': [
      CategoryDish(id: 'c-mh-b1', name: 'Misal Pav', description: 'Sprouted bean curry topped with farsan and pav.', timeMinutes: 40),
      CategoryDish(id: 'c-mh-b2', name: 'Poha', description: 'Flattened rice with peanuts and curry leaves.', timeMinutes: 20),
      CategoryDish(id: 'c-mh-b3', name: 'Sabudana Khichdi', description: 'Tapioca pearls with peanuts and lemon.', timeMinutes: 25),
      CategoryDish(id: 'c-mh-b4', name: 'Thalipeeth', description: 'Multi-grain flatbread with herbs.', timeMinutes: 35),
      CategoryDish(id: 'c-mh-b5', name: 'Rava Upma', description: 'Semolina with vegetables and ghee.', timeMinutes: 20),
    ],
    'healthy': [
      CategoryDish(id: 'c-mh-h1', name: 'Matki Usal', description: 'Sprouted moth beans, light on oil.', timeMinutes: 30),
      CategoryDish(id: 'c-mh-h2', name: 'Moong Dal Bhaat', description: 'Rice and moong dal with turmeric.', timeMinutes: 30),
      CategoryDish(id: 'c-mh-h3', name: 'Bharlivangi', description: 'Stuffed brinjal, simmered not fried.', timeMinutes: 40),
      CategoryDish(id: 'c-mh-h4', name: 'Shengdana Chutney Rice', description: 'Peanut chutney rice, easy and filling.', timeMinutes: 25),
      CategoryDish(id: 'c-mh-h5', name: 'Karela Sakhar Bhaaji', description: 'Bitter gourd cooked with jaggery balance.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-mh-d1', name: 'Puran Poli', description: 'Sweet chana dal stuffed flatbread.', timeMinutes: 60),
      CategoryDish(id: 'c-mh-d2', name: 'Varhadi Mutton', description: 'Rustic mutton curry with strong spices.', timeMinutes: 85),
      CategoryDish(id: 'c-mh-d3', name: 'Kolhapuri Chicken', description: 'Fiery chicken with red chilli masala.', timeMinutes: 55),
      CategoryDish(id: 'c-mh-d4', name: 'Amti', description: 'Toor dal with kokum and goda masala.', timeMinutes: 35),
      CategoryDish(id: 'c-mh-d5', name: 'Pandhra Rassa Chicken', description: 'White chicken curry with poppy seeds.', timeMinutes: 55),
    ],
    'veg': [
      CategoryDish(id: 'c-mh-v1', name: 'Bharlivangi', description: 'Stuffed brinjal with peanut masala.', timeMinutes: 40),
      CategoryDish(id: 'c-mh-v2', name: 'Zunka', description: 'Gram-flour crumble with onions and garlic.', timeMinutes: 30),
      CategoryDish(id: 'c-mh-v3', name: 'Pav Bhaji', description: 'Spiced vegetable mash with buttered pav.', timeMinutes: 40),
      CategoryDish(id: 'c-mh-v4', name: 'Bharli Vangi-special', description: 'Baby brinjal stuffed and simmered.', timeMinutes: 45),
      CategoryDish(id: 'c-mh-v5', name: 'Vangyache Bharit', description: 'Roasted eggplant mash with garlic.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-mh-n1', name: 'Kolhapuri Mutton', description: 'Mutton with fiery Kolhapuri masala.', timeMinutes: 90),
      CategoryDish(id: 'c-mh-n2', name: 'Prawn Koliwada', description: 'Crisp marinated prawns from Mumbai.', timeMinutes: 30),
      CategoryDish(id: 'c-mh-n3', name: 'Bombil Fry', description: 'Bombay duck fish, crisp and spiced.', timeMinutes: 25),
      CategoryDish(id: 'c-mh-n4', name: 'Chicken Sukka', description: 'Dry coconut chicken with curry leaves.', timeMinutes: 50),
      CategoryDish(id: 'c-mh-n5', name: 'Mutton Sukha', description: 'Dry mutton with roasted spices.', timeMinutes: 85),
    ],
    'sweet': [
      CategoryDish(id: 'c-mh-s1', name: 'Modak', description: 'Steamed dumplings with coconut-jaggery filling.', timeMinutes: 60),
      CategoryDish(id: 'c-mh-s2', name: 'Puran Poli', description: 'Sweet flatbread with chana dal stuffing.', timeMinutes: 60),
      CategoryDish(id: 'c-mh-s3', name: 'Shrikhand', description: 'Hung curd with saffron and cardamom.', timeMinutes: 30),
      CategoryDish(id: 'c-mh-s4', name: 'Karanji', description: 'Fried crescents with coconut filling.', timeMinutes: 45),
      CategoryDish(id: 'c-mh-s5', name: 'Gul Poli', description: 'Jaggery-stuffed sweet flatbread.', timeMinutes: 45),
    ],
    'kids': [
      CategoryDish(id: 'c-mh-k1', name: 'Mini Sabudana Khichdi', description: 'Small tapioca pearls, mildly spiced.', timeMinutes: 25),
      CategoryDish(id: 'c-mh-k2', name: 'Poha Bites', description: 'Lemon poha with peanuts.', timeMinutes: 20),
      CategoryDish(id: 'c-mh-k3', name: 'Pav Bhaji Lite', description: 'Milder pav bhaji for little ones.', timeMinutes: 35),
      CategoryDish(id: 'c-mh-k4', name: 'Puran Poli Slice', description: 'Sweet stuffed bread in small slices.', timeMinutes: 50),
      CategoryDish(id: 'c-mh-k5', name: 'Modak Mini', description: 'Small sweet steamed dumplings.', timeMinutes: 50),
    ],
  },
  'goan': {
    'breakfast': [
      CategoryDish(id: 'c-go-b1', name: 'Sanna with Poee', description: 'Steamed rice cakes with Goa\'s leavened bread.', timeMinutes: 30),
      CategoryDish(id: 'c-go-b2', name: 'Pao with Egg Bhurji', description: 'Crusty pao with spiced scrambled eggs.', timeMinutes: 20),
      CategoryDish(id: 'c-go-b3', name: 'Goan Poha', description: 'Flattened rice with coconut and curry leaves.', timeMinutes: 20),
      CategoryDish(id: 'c-go-b4', name: 'Chicken Cutlet Pao', description: 'Crisp chicken cutlets in a warm bun.', timeMinutes: 35),
      CategoryDish(id: 'c-go-b5', name: 'Bread Omelette', description: 'Goan-style omelette sandwiched in bread.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-go-h1', name: 'Vegetable Xacuti-light', description: 'A lighter vegetable roast with coconut.', timeMinutes: 40),
      CategoryDish(id: 'c-go-h2', name: 'Tawa Fish', description: 'Lightly spiced fish cooked on the tawa.', timeMinutes: 25),
      CategoryDish(id: 'c-go-h3', name: 'Khatkhate', description: 'Mixed vegetable stew with kokum.', timeMinutes: 40),
      CategoryDish(id: 'c-go-h4', name: 'Prawn Balchao Salad', description: 'Tangy pickled prawn on greens.', timeMinutes: 30),
      CategoryDish(id: 'c-go-h5', name: 'Coconut Rice', description: 'Light rice tossed with fresh coconut.', timeMinutes: 25),
    ],
    'dinner': [
      CategoryDish(id: 'c-go-d1', name: 'Goan Fish Curry', description: 'Tangy coconut fish curry with kokum.', timeMinutes: 40),
      CategoryDish(id: 'c-go-d2', name: 'Chicken Cafreal', description: 'Green masala-marinated chicken.', timeMinutes: 50),
      CategoryDish(id: 'c-go-d3', name: 'Pork Vindaloo', description: 'Fiery pork with vinegar and spices.', timeMinutes: 75),
      CategoryDish(id: 'c-go-d4', name: 'Xacuti', description: 'Roasted coconut and poppy seed curry.', timeMinutes: 60),
      CategoryDish(id: 'c-go-d5', name: 'Sorpotel-style Pork', description: 'Pork in a tangy spice blend.', timeMinutes: 70),
    ],
    'veg': [
      CategoryDish(id: 'c-go-v1', name: 'Khatkhate', description: 'Goan vegetable stew with coconut.', timeMinutes: 40),
      CategoryDish(id: 'c-go-v2', name: 'Aloo Bhoplya', description: 'Potato and pumpkin curry.', timeMinutes: 30),
      CategoryDish(id: 'c-go-v3', name: 'Bondas', description: 'Spiced potato fritters.', timeMinutes: 30),
      CategoryDish(id: 'c-go-v4', name: 'Veg Xacuti', description: 'Vegetables in roasted coconut gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-go-v5', name: 'Cabbage Foogath', description: 'Stir-fried cabbage with coconut.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-go-n1', name: 'Pork Vindaloo', description: 'Vinegary pork curry with red chillies.', timeMinutes: 75),
      CategoryDish(id: 'c-go-n2', name: 'Prawn Curry', description: 'Prawns in coconut milk with kokum.', timeMinutes: 35),
      CategoryDish(id: 'c-go-n3', name: 'Chicken Xacuti', description: 'Chicken in a roasted spice-coconut gravy.', timeMinutes: 55),
      CategoryDish(id: 'c-go-n4', name: 'Fish Recheado', description: 'Fish stuffed with fiery red masala.', timeMinutes: 45),
      CategoryDish(id: 'c-go-n5', name: 'Beef Chilli Fry', description: 'Spicy beef stir-fry from the coastal kitchen.', timeMinutes: 50),
    ],
    'sweet': [
      CategoryDish(id: 'c-go-s1', name: 'Bebinca', description: 'Goa\'s layered coconut-egg pudding.', timeMinutes: 90),
      CategoryDish(id: 'c-go-s2', name: 'Dodol', description: 'Dark coconut-jaggery toffee cake.', timeMinutes: 70),
      CategoryDish(id: 'c-go-s3', name: 'Doce', description: 'Sweet coconut and semolina morsels.', timeMinutes: 40),
      CategoryDish(id: 'c-go-s4', name: 'Neureos', description: 'Fried crescents with coconut filling.', timeMinutes: 45),
      CategoryDish(id: 'c-go-s5', name: 'Sanna Sweet', description: 'Sweet steamed rice cakes.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-go-k1', name: 'Butter Pao', description: 'Warm crusty bread with butter.', timeMinutes: 10),
      CategoryDish(id: 'c-go-k2', name: 'Sweet Sanna', description: 'Soft sweet rice cakes.', timeMinutes: 30),
      CategoryDish(id: 'c-go-k3', name: 'Potato Bonda', description: 'Crispy spiced potato bites.', timeMinutes: 30),
      CategoryDish(id: 'c-go-k4', name: 'Coconut Poha', description: 'Flattened rice with coconut and sugar.', timeMinutes: 20),
      CategoryDish(id: 'c-go-k5', name: 'Bebinca Slice', description: 'A small slice of layered pudding.', timeMinutes: 80),
    ],
  },
  'sindhi': {
    'breakfast': [
      CategoryDish(id: 'c-sn-b1', name: 'Koki', description: 'Whole-wheat pan flatbread with onion and coriander.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-b2', name: 'Sai Bhaji Breakfast', description: 'Mild spinach and dal porridge.', timeMinutes: 30),
      CategoryDish(id: 'c-sn-b3', name: 'Doda Breakfast', description: 'Sindhi flatbread with a coarse bite.', timeMinutes: 30),
      CategoryDish(id: 'c-sn-b4', name: 'Chaa with Pappad', description: 'Crisp papad with spiced tea.', timeMinutes: 10),
      CategoryDish(id: 'c-sn-b5', name: 'Bhee Aloo', description: 'Lotus stem and potato breakfast fry.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-sn-h1', name: 'Sai Bhaji', description: 'Spinach, dal and vegetable mash.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-h2', name: 'Tuk Tuk Raita', description: 'Cucumber and onion yogurt salad.', timeMinutes: 15),
      CategoryDish(id: 'c-sn-h3', name: 'Bhuga Chawar', description: 'Lemon-yogurt rice, easy on the oil.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-h4', name: 'Kadhi Light', description: 'Sindhi kadhi, a lighter version.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-h5', name: 'Moong Dal Sindhi', description: 'Mung dal with fenugreek leaves.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-sn-d1', name: 'Sai Bhaji with Rice', description: 'Spinach-dal mash served with rice.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-d2', name: 'Kadhi', description: 'Sindhi kadhi with gram-flour pakoras.', timeMinutes: 45),
      CategoryDish(id: 'c-sn-d3', name: 'Bhuga Chawar', description: 'Steamed rice with spiced lentils.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-d4', name: 'Sindhi Mutton', description: 'Mutton curry with tomatoes and ginger.', timeMinutes: 85),
      CategoryDish(id: 'c-sn-d5', name: 'Palak Dal', description: 'Spinach with toor dal and garlic.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-sn-v1', name: 'Sai Bhaji', description: 'The Sindhi staple of greens and dal.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-v2', name: 'Koki', description: 'Crisp whole-wheat flatbread.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-v3', name: 'Bhuga Chawar', description: 'Savory yogurt-tempered rice.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-v4', name: 'Bhee Aloo', description: 'Lotus stem with potatoes in masala.', timeMinutes: 30),
      CategoryDish(id: 'c-sn-v5', name: 'Sindhi Kadhi', description: 'Tamarind-kadhi with vegetables and pakoras.', timeMinutes: 45),
    ],
    'nonveg': [
      CategoryDish(id: 'c-sn-n1', name: 'Sindhi Fish Curry', description: 'Fish in a tomato-tamarind gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-n2', name: 'Chicken Sindhi', description: 'Chicken with onions, tomatoes and ginger.', timeMinutes: 55),
      CategoryDish(id: 'c-sn-n3', name: 'Mutton Saag', description: 'Mutton cooked with greens.', timeMinutes: 85),
      CategoryDish(id: 'c-sn-n4', name: 'Fish Palla', description: 'Hilsa-style fish with mustard.', timeMinutes: 45),
      CategoryDish(id: 'c-sn-n5', name: 'Egg Bhuga', description: 'Spiced scrambled eggs Sindhi style.', timeMinutes: 20),
    ],
    'sweet': [
      CategoryDish(id: 'c-sn-s1', name: 'Sindhi Ladoo', description: 'Besan and ghee laddoos.', timeMinutes: 30),
      CategoryDish(id: 'c-sn-s2', name: 'Kheer Sindhi', description: 'Rice pudding with cardamom.', timeMinutes: 40),
      CategoryDish(id: 'c-sn-s3', name: 'Gulab Jamun', description: 'Milk dumplings in rose syrup.', timeMinutes: 45),
      CategoryDish(id: 'c-sn-s4', name: 'Mohan Singhar', description: 'Saffron sweetened almonds.', timeMinutes: 20),
      CategoryDish(id: 'c-sn-s5', name: 'Halwa Sindhi', description: 'Wheat halwa with ghee and nuts.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-sn-k1', name: 'Mini Koki', description: 'Small crisp flatbreads with butter.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-k2', name: 'Sweet Chaa Rice', description: 'Rice with jaggery and cardamom.', timeMinutes: 20),
      CategoryDish(id: 'c-sn-k3', name: 'Crispy Papad Bites', description: 'Crushed papad with lemon.', timeMinutes: 10),
      CategoryDish(id: 'c-sn-k4', name: 'Aloo Bites', description: 'Spiced potato cutlets.', timeMinutes: 25),
      CategoryDish(id: 'c-sn-k5', name: 'Kheer Cup', description: 'Small cup of rice pudding.', timeMinutes: 35),
    ],
  },
  'hyderabadi': {
    'breakfast': [
      CategoryDish(id: 'c-yd-b1', name: 'Hyderabadi Dosa', description: 'Crisp dosa with potato masala.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-b2', name: 'Malai Bread Toast', description: 'Sweet bread toast with cream.', timeMinutes: 15),
      CategoryDish(id: 'c-yd-b3', name: 'Kichdi Breakfast', description: 'Mild rice-lentil porridge with ghee.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-b4', name: 'Pesarattu', description: 'Green moong dosa with ginger chutney.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-b5', name: 'Bun Maska', description: 'Soft bun with butter, Old City style.', timeMinutes: 10),
    ],
    'healthy': [
      CategoryDish(id: 'c-yd-h1', name: 'Methi Dal', description: 'Fenugreek with toor dal, light.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-h2', name: 'Vegetable Pulusu', description: 'Tangy vegetable stew, low oil.', timeMinutes: 35),
      CategoryDish(id: 'c-yd-h3', name: 'Sprout Salad', description: 'Sprouted lentils with lime and herbs.', timeMinutes: 15),
      CategoryDish(id: 'c-yd-h4', name: 'Palak Pappu', description: 'Spinach and toor dal simmered.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-h5', name: 'Bagara Khana-light', description: 'Lightly spiced tamarind rice.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-yd-d1', name: 'Hyderabadi Biryani', description: 'Aromatic rice layered with spiced meat.', timeMinutes: 70),
      CategoryDish(id: 'c-yd-d2', name: 'Mirchi ka Salan', description: 'Green chillies in a peanut-sesame gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-yd-d3', name: 'Bagara Baingan', description: 'Baby brinjal in a peanut-tamarind curry.', timeMinutes: 45),
      CategoryDish(id: 'c-yd-d4', name: 'Double ka Meetha-savory', description: 'Bread pudding turned savory side.', timeMinutes: 35),
      CategoryDish(id: 'c-yd-d5', name: 'Kheema Biryani', description: 'Minced meat layered rice.', timeMinutes: 60),
    ],
    'veg': [
      CategoryDish(id: 'c-yd-v1', name: 'Bagara Baingan', description: 'Stuffed brinjal in a rich sauce.', timeMinutes: 45),
      CategoryDish(id: 'c-yd-v2', name: 'Mirchi ka Salan', description: 'Chillies in peanut gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-yd-v3', name: 'Pappu', description: 'Simple toor dal with tamarind.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-v4', name: 'Veg Dum Biryani', description: 'Layered vegetable biryani.', timeMinutes: 60),
      CategoryDish(id: 'c-yd-v5', name: 'Hyderabadi Tamatar Curry', description: 'Tangy tomato curry with spices.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-yd-n1', name: 'Chicken 65', description: 'Fiery fried chicken bites.', timeMinutes: 35),
      CategoryDish(id: 'c-yd-n2', name: 'Hyderabadi Chicken Biryani', description: 'Chicken biryani with saffron and mint.', timeMinutes: 70),
      CategoryDish(id: 'c-yd-n3', name: 'Nihari', description: 'Slow-braised meat stew with marrow.', timeMinutes: 90),
      CategoryDish(id: 'c-yd-n4', name: 'Mutton Haleem', description: 'Pounded meat and wheat porridge.', timeMinutes: 90),
      CategoryDish(id: 'c-yd-n5', name: 'Kheema Naan', description: 'Minced lamb stuffed naan.', timeMinutes: 50),
    ],
    'sweet': [
      CategoryDish(id: 'c-yd-s1', name: 'Double ka Meetha', description: 'Bread pudding with saffron and nuts.', timeMinutes: 45),
      CategoryDish(id: 'c-yd-s2', name: 'Qubani ka Meetha', description: 'Apricot dessert with cream.', timeMinutes: 35),
      CategoryDish(id: 'c-yd-s3', name: 'Shahi Tukda', description: 'Fried bread in saffron milk.', timeMinutes: 40),
      CategoryDish(id: 'c-yd-s4', name: 'Khubani Halwa', description: 'Dried apricot halwa.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-s5', name: 'Badam Ki Jaali', description: 'Almond sweet lattice.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-yd-k1', name: 'Malai Bun', description: 'Sweet cream-filled bun.', timeMinutes: 15),
      CategoryDish(id: 'c-yd-k2', name: 'Mini Pesarattu', description: 'Small moong dosas with chutney.', timeMinutes: 30),
      CategoryDish(id: 'c-yd-k3', name: 'Sweet Rice Bowl', description: 'Jaggery-sweetened rice.', timeMinutes: 20),
      CategoryDish(id: 'c-yd-k4', name: 'Double Meetha Cup', description: 'Small bread pudding cup.', timeMinutes: 40),
      CategoryDish(id: 'c-yd-k5', name: 'Butter Bun', description: 'Warm bun with butter and sugar.', timeMinutes: 10),
    ],
  },
};
