import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart5 = {
  'chinese': {
    'breakfast': [
      CategoryDish(id: 'c-ch-b1', name: 'Egg Fried Rice', description: 'Wok-tossed rice with egg and scallion.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-b2', name: 'Spring Onion Pancake', description: 'Flaky scallion pancake.', timeMinutes: 30),
      CategoryDish(id: 'c-ch-b3', name: 'Congee', description: 'Silky rice porridge with ginger.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-b4', name: 'Dim Sum Steamed Buns', description: 'Soft buns with a savoury filling.', timeMinutes: 45),
      CategoryDish(id: 'c-ch-b5', name: 'Chinese Omelette', description: 'Folded omelette with spring onion.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-ch-h1', name: 'Steamed Veg Dumplings', description: 'Light dumplings with crisp veg.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-h2', name: 'Stir-Fried Greens', description: 'Bok choy with garlic and soy.', timeMinutes: 15),
      CategoryDish(id: 'c-ch-h3', name: 'Chicken Broth Soup', description: 'Clear comforting chicken soup.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-h4', name: 'Tofu Stir-Fry', description: 'Crisp tofu with vegetables.', timeMinutes: 25),
      CategoryDish(id: 'c-ch-h5', name: 'Cucumber Salad Chinese', description: 'Cooled cucumber with sesame.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-ch-d1', name: 'Kung Pao Chicken', description: 'Chicken with peanuts and chilli.', timeMinutes: 35),
      CategoryDish(id: 'c-ch-d2', name: 'Hakka Noodles', description: 'Wok noodles with vegetables.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-d3', name: 'Sweet and Sour Pork', description: 'Pork in a glossy sweet-sour sauce.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-d4', name: 'Chilli Garlic Noodles', description: 'Fiery noodles with garlic.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-d5', name: 'Fried Rice Chinese', description: 'Classic wok-fried rice.', timeMinutes: 20),
    ],
    'veg': [
      CategoryDish(id: 'c-ch-v1', name: 'Veg Manchurian', description: 'Crisp veg dumplings in soy gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-v2', name: 'Chilli Paneer', description: 'Paneer tossed in a spicy sauce.', timeMinutes: 25),
      CategoryDish(id: 'c-ch-v3', name: 'Veg Hakka Noodles', description: 'Vegetable wok noodles.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-v4', name: 'Tofu in Garlic Sauce', description: 'Silken tofu, savoury and glossy.', timeMinutes: 25),
      CategoryDish(id: 'c-ch-v5', name: 'Mixed Veg Fried Rice', description: 'Fried rice with seasonal veg.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ch-n1', name: 'Kung Pao Chicken', description: 'Nuts and chicken in a spicy sauce.', timeMinutes: 35),
      CategoryDish(id: 'c-ch-n2', name: 'Dragon Chicken', description: 'Crisp chicken in a spicy glaze.', timeMinutes: 35),
      CategoryDish(id: 'c-ch-n3', name: 'Chilli Prawns', description: 'Prawns tossed with dried chilli.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-n4', name: 'Chicken Manchurian', description: 'Fried chicken in soy-chilli gravy.', timeMinutes: 35),
      CategoryDish(id: 'c-ch-n5', name: 'Sweet and Sour Chicken', description: 'Chicken in a glossy tangy sauce.', timeMinutes: 40),
    ],
    'sweet': [
      CategoryDish(id: 'c-ch-s1', name: 'Fried Banana with Honey', description: 'Crisp banana drizzled with honey.', timeMinutes: 15),
      CategoryDish(id: 'c-ch-s2', name: 'Sesame Balls', description: 'Glutinous balls with red bean paste.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-s3', name: 'Mango Pudding', description: 'Silky chilled mango pudding.', timeMinutes: 30),
      CategoryDish(id: 'c-ch-s4', name: 'Almond Jelly', description: 'Light almond-flavoured jelly.', timeMinutes: 30),
      CategoryDish(id: 'c-ch-s5', name: 'Sweet Red Bean Soup', description: 'Warm sweet bean dessert soup.', timeMinutes: 35),
    ],
    'kids': [
      CategoryDish(id: 'c-ch-k1', name: 'Fried Rice Bowl', description: 'Mild egg fried rice.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-k2', name: 'Noodle Cup', description: 'Small portion of veg noodles.', timeMinutes: 20),
      CategoryDish(id: 'c-ch-k3', name: 'Crispy Banana', description: 'Sweet fried banana pieces.', timeMinutes: 15),
      CategoryDish(id: 'c-ch-k4', name: 'Dim Sum Bite', description: 'Small steamed bun.', timeMinutes: 40),
      CategoryDish(id: 'c-ch-k5', name: 'Fried Corn Kernels', description: 'Crisp sweetcorn bites.', timeMinutes: 15),
    ],
  },
  'indo_chinese': {
    'breakfast': [
      CategoryDish(id: 'c-ic-b1', name: 'Hakka Noodles Breakfast', description: 'Quick wok noodles with egg.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-b2', name: 'Desi Chilli Toast', description: 'Spiced toast with a chilli kick.', timeMinutes: 15),
      CategoryDish(id: 'c-ic-b3', name: 'Veg Fried Rice Bowl', description: 'Morning fried rice with veggies.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-b4', name: 'Spring Rolls', description: 'Crisp rolls with a veg filling.', timeMinutes: 30),
      CategoryDish(id: 'c-ic-b5', name: 'Cheese Garlic Bread', description: 'Buttery bread with garlic and cheese.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-ic-h1', name: 'Steamed Wontons', description: 'Light steamed parcels with filling.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-h2', name: 'Stir-Fried Veggies', description: 'Crisp vegetables in light soy.', timeMinutes: 15),
      CategoryDish(id: 'c-ic-h3', name: 'Clear Veg Soup', description: 'Light broth with vegetables.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-h4', name: 'Lemon Chilli Tofu', description: 'Zesty pan-seared tofu.', timeMinutes: 25),
      CategoryDish(id: 'c-ic-h5', name: 'Cabbage Salad', description: 'Shredded cabbage with sesame.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-ic-d1', name: 'Chilli Chicken', description: 'Crisp chicken in a fiery sauce.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-d2', name: 'Veg Manchurian', description: 'Vegetable dumplings in soy gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-ic-d3', name: 'Chilli Garlic Noodles', description: 'Spicy garlic noodles.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-d4', name: 'Schezwan Fried Rice', description: 'Punchy rice with schezwan sauce.', timeMinutes: 25),
      CategoryDish(id: 'c-ic-d5', name: 'Chicken 65', description: 'Crisp, spicy south-style chicken.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-ic-v1', name: 'Gobi Manchurian', description: 'Cauliflower in a spicy soy gravy.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-v2', name: 'Paneer Chilli', description: 'Paneer tossed with peppers.', timeMinutes: 25),
      CategoryDish(id: 'c-ic-v3', name: 'Veg Hakka Noodles', description: 'Classic veggie wok noodles.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-v4', name: 'Veg Manchurian Dry', description: 'Dry-style veg dumplings.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-v5', name: 'Veg Schezwan Rice', description: 'Spicy vegetable fried rice.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ic-n1', name: 'Chilli Chicken', description: 'The classic indo-chinese favourite.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-n2', name: 'Chicken Manchurian', description: 'Fried chicken in soy gravy.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-n3', name: 'Egg Fried Rice', description: 'Wok rice with scrambled egg.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-n4', name: 'Schezwan Chicken', description: 'Chicken in a fiery schezwan sauce.', timeMinutes: 35),
      CategoryDish(id: 'c-ic-n5', name: 'Chicken Spring Rolls', description: 'Crisp rolls filled with chicken.', timeMinutes: 35),
    ],
    'sweet': [
      CategoryDish(id: 'c-ic-s1', name: 'Honey Chilli Bite', description: 'Crisp sweet-spicy bites.', timeMinutes: 25),
      CategoryDish(id: 'c-ic-s2', name: 'Custard Parfait', description: 'Layered custard with fruit.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-s3', name: 'Fried Ice Cream', description: 'Crisp-coated frozen dessert.', timeMinutes: 25),
      CategoryDish(id: 'c-ic-s4', name: 'Banana Honey Fry', description: 'Warm honey-glazed banana.', timeMinutes: 15),
      CategoryDish(id: 'c-ic-s5', name: 'Choco Spring Roll', description: 'Chocolate-filled crisp rolls.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-ic-k1', name: 'Noodle Bowl', description: 'Mild veg noodles for kids.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-k2', name: 'Fried Rice Cup', description: 'Small mild fried rice.', timeMinutes: 20),
      CategoryDish(id: 'c-ic-k3', name: 'Spring Roll Bite', description: 'Crispy veggie rolls.', timeMinutes: 30),
      CategoryDish(id: 'c-ic-k4', name: 'Honey Banana', description: 'Sweet banana pieces.', timeMinutes: 15),
      CategoryDish(id: 'c-ic-k5', name: 'Cheese Toast', description: 'Golden cheese toast triangles.', timeMinutes: 10),
    ],
  },
  'italian': {
    'breakfast': [
      CategoryDish(id: 'c-it-b1', name: 'Frittata', description: 'Baked egg bake with vegetables.', timeMinutes: 30),
      CategoryDish(id: 'c-it-b2', name: 'Crostini with Tomatoes', description: 'Toasted bread with fresh tomato.', timeMinutes: 15),
      CategoryDish(id: 'c-it-b3', name: 'Ricotta Toast', description: 'Toast topped with creamy ricotta.', timeMinutes: 10),
      CategoryDish(id: 'c-it-b4', name: 'Bruschetta', description: 'Garlic toast with tomato and basil.', timeMinutes: 15),
      CategoryDish(id: 'c-it-b5', name: 'Panettone Toast', description: 'Sweet holiday bread, lightly toasted.', timeMinutes: 10),
    ],
    'healthy': [
      CategoryDish(id: 'c-it-h1', name: 'Caprese Salad', description: 'Tomato, mozzarella and basil.', timeMinutes: 10),
      CategoryDish(id: 'c-it-h2', name: 'Grilled Vegetable Platter', description: 'Charred seasonal vegetables.', timeMinutes: 25),
      CategoryDish(id: 'c-it-h3', name: 'Minestrone Soup', description: 'Hearty vegetable soup with pasta.', timeMinutes: 40),
      CategoryDish(id: 'c-it-h4', name: 'Lemon Garlic Chicken', description: 'Light chicken with lemon and herbs.', timeMinutes: 30),
      CategoryDish(id: 'c-it-h5', name: 'Insalata Verde', description: 'Fresh green salad with vinaigrette.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-it-d1', name: 'Spaghetti Carbonara', description: 'Pasta with egg, cheese and pancetta.', timeMinutes: 30),
      CategoryDish(id: 'c-it-d2', name: 'Margherita Pizza', description: 'Classic tomato, mozzarella and basil.', timeMinutes: 30),
      CategoryDish(id: 'c-it-d3', name: 'Lasagna', description: 'Layered pasta with bolognese and béchamel.', timeMinutes: 70),
      CategoryDish(id: 'c-it-d4', name: 'Risotto ai Funghi', description: 'Creamy mushroom risotto.', timeMinutes: 40),
      CategoryDish(id: 'c-it-d5', name: 'Chicken Parmesan', description: 'Crisp chicken with marinara and cheese.', timeMinutes: 45),
    ],
    'veg': [
      CategoryDish(id: 'c-it-v1', name: 'Penne Arrabbiata', description: 'Pasta in a spicy tomato sauce.', timeMinutes: 30),
      CategoryDish(id: 'c-it-v2', name: 'Vegetable Risotto', description: 'Creamy rice with vegetables.', timeMinutes: 40),
      CategoryDish(id: 'c-it-v3', name: 'Pizza Margherita', description: 'Simple and classic.', timeMinutes: 30),
      CategoryDish(id: 'c-it-v4', name: 'Eggplant Parmigiana', description: 'Baked aubergine with cheese.', timeMinutes: 55),
      CategoryDish(id: 'c-it-v5', name: 'Caprese Salad', description: 'Tomato and mozzarella classic.', timeMinutes: 10),
    ],
    'nonveg': [
      CategoryDish(id: 'c-it-n1', name: 'Spaghetti Carbonara', description: 'Rich pasta with guanciale.', timeMinutes: 30),
      CategoryDish(id: 'c-it-n2', name: 'Chicken Parmesan', description: 'Parmesan-crusted chicken.', timeMinutes: 45),
      CategoryDish(id: 'c-it-n3', name: 'Amatriciana', description: 'Pasta with tomatoes and pork cheek.', timeMinutes: 30),
      CategoryDish(id: 'c-it-n4', name: 'Salmon Pasta', description: 'Pasta with flaked salmon and lemon.', timeMinutes: 25),
      CategoryDish(id: 'c-it-n5', name: 'Shrimp Scampi', description: 'Garlic-butter shrimp with pasta.', timeMinutes: 25),
    ],
    'sweet': [
      CategoryDish(id: 'c-it-s1', name: 'Tiramisu', description: 'Espresso-soaked dessert with mascarpone.', timeMinutes: 40),
      CategoryDish(id: 'c-it-s2', name: 'Panna Cotta', description: 'Silky vanilla cream with berry sauce.', timeMinutes: 30),
      CategoryDish(id: 'c-it-s3', name: 'Cannoli', description: 'Crisp shells with sweet ricotta.', timeMinutes: 40),
      CategoryDish(id: 'c-it-s4', name: 'Gelato', description: 'Homemade vanilla ice cream.', timeMinutes: 40),
      CategoryDish(id: 'c-it-s5', name: 'Zabaglione', description: 'Warm marsala custard.', timeMinutes: 20),
    ],
    'kids': [
      CategoryDish(id: 'c-it-k1', name: 'Cheesy Pasta', description: 'Mac and cheese the simple way.', timeMinutes: 20),
      CategoryDish(id: 'c-it-k2', name: 'Mini Pizza', description: 'Small pizzas kids can top.', timeMinutes: 25),
      CategoryDish(id: 'c-it-k3', name: 'Garlic Breadsticks', description: 'Soft sticks with garlic butter.', timeMinutes: 25),
      CategoryDish(id: 'c-it-k4', name: 'Spaghetti with Meatballs', description: 'Mild meatballs in tomato sauce.', timeMinutes: 35),
      CategoryDish(id: 'c-it-k5', name: 'Fruit Gelato Cup', description: 'Small scoop of ice cream.', timeMinutes: 10),
    ],
  },
  'japanese': {
    'breakfast': [
      CategoryDish(id: 'c-ja-b1', name: 'Tamagoyaki', description: 'Rolled Japanese omelette.', timeMinutes: 15),
      CategoryDish(id: 'c-ja-b2', name: 'Miso Soup', description: 'Warm broth with tofu and wakame.', timeMinutes: 20),
      CategoryDish(id: 'c-ja-b3', name: 'Onigiri', description: 'Rice balls with a savoury filling.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-b4', name: 'Grilled Fish Breakfast', description: 'Lightly grilled fish with rice.', timeMinutes: 25),
      CategoryDish(id: 'c-ja-b5', name: 'Tamago Sando', description: 'Egg sandwich on soft milk bread.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-ja-h1', name: 'Miso Soup', description: 'Light, warming and nutritious.', timeMinutes: 20),
      CategoryDish(id: 'c-ja-h2', name: 'Sashimi Salad', description: 'Fresh fish over greens.', timeMinutes: 15),
      CategoryDish(id: 'c-ja-h3', name: 'Steamed Vegetables', description: 'Gohan-style steamed veg with ponzu.', timeMinutes: 20),
      CategoryDish(id: 'c-ja-h4', name: 'Edamame', description: 'Steamed soybeans with sea salt.', timeMinutes: 10),
      CategoryDish(id: 'c-ja-h5', name: 'Chicken and Rice Bowl', description: 'Mild seasoned chicken over rice.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-ja-d1', name: 'Chicken Teriyaki', description: 'Glazed chicken with sticky teriyaki.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-d2', name: 'Sushi Rolls', description: 'Hand-rolled maki with fresh fillings.', timeMinutes: 45),
      CategoryDish(id: 'c-ja-d3', name: 'Ramen', description: 'Rich noodle soup with soft egg.', timeMinutes: 40),
      CategoryDish(id: 'c-ja-d4', name: 'Katsu Curry', description: 'Crisp cutlet with curry sauce.', timeMinutes: 40),
      CategoryDish(id: 'c-ja-d5', name: 'Yakitori', description: 'Charred chicken skewers with tare.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-ja-v1', name: 'Vegetable Tempura', description: 'Crisp battered vegetables.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-v2', name: 'Agedashi Tofu', description: 'Fried tofu in a light dashi sauce.', timeMinutes: 25),
      CategoryDish(id: 'c-ja-v3', name: 'Miso Ramen Veg', description: 'Vegetarian miso noodle soup.', timeMinutes: 35),
      CategoryDish(id: 'c-ja-v4', name: 'Onigiri Veg', description: 'Rice balls with pickled filling.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-v5', name: 'Gomae', description: 'Spinach with sesame dressing.', timeMinutes: 15),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ja-n1', name: 'Chicken Teriyaki', description: 'Savoury-sweet glazed chicken.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-n2', name: 'Salmon Teriyaki', description: 'Glazed salmon fillet.', timeMinutes: 25),
      CategoryDish(id: 'c-ja-n3', name: 'Katsu Chicken', description: 'Panko-crisp chicken cutlet.', timeMinutes: 35),
      CategoryDish(id: 'c-ja-n4', name: 'Tonkotsu Ramen', description: 'Rich pork broth noodle soup.', timeMinutes: 45),
      CategoryDish(id: 'c-ja-n5', name: 'Shrimp Tempura', description: 'Crisp battered prawns.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-ja-s1', name: 'Matcha Mochi', description: 'Soft chewy green-tea sweets.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-s2', name: 'Dorayaki', description: 'Pancakes with sweet red bean.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-s3', name: 'Sakura Mochi', description: 'Pink rice cakes with bean paste.', timeMinutes: 35),
      CategoryDish(id: 'c-ja-s4', name: 'Anmitsu', description: 'Agar jelly dessert with fruit.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-s5', name: 'Castella', description: 'Light fluffy sponge cake.', timeMinutes: 45),
    ],
    'kids': [
      CategoryDish(id: 'c-ja-k1', name: 'Onigiri Bite', description: 'Small rice balls, easy to hold.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-k2', name: 'Tamago Sando', description: 'Soft egg sandwich.', timeMinutes: 15),
      CategoryDish(id: 'c-ja-k3', name: 'Corn Croquette', description: 'Crisp golden corn fritters.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-k4', name: 'Dorayaki', description: 'Sweet bean pancakes.', timeMinutes: 30),
      CategoryDish(id: 'c-ja-k5', name: 'Chicken Nuggets Japanese', description: 'Crisp bite-sized chicken.', timeMinutes: 30),
    ],
  },
  'thai': {
    'breakfast': [
      CategoryDish(id: 'c-th-b1', name: 'Thai Omelette', description: 'Crisp-edged omelette with rice.', timeMinutes: 15),
      CategoryDish(id: 'c-th-b2', name: 'Khao Tom', description: 'Thai rice soup with chicken.', timeMinutes: 25),
      CategoryDish(id: 'c-th-b3', name: 'Banana Pancake', description: 'Sweet street-style banana pancake.', timeMinutes: 20),
      CategoryDish(id: 'c-th-b4', name: 'Thai Green Salad', description: 'Crisp salad with lime dressing.', timeMinutes: 15),
      CategoryDish(id: 'c-th-b5', name: 'Jok', description: 'Silky rice porridge with ginger.', timeMinutes: 35),
    ],
    'healthy': [
      CategoryDish(id: 'c-th-h1', name: 'Tom Yum Soup', description: 'Hot and sour soup with herbs.', timeMinutes: 25),
      CategoryDish(id: 'c-th-h2', name: 'Thai Green Curry Light', description: 'Fragrant curry with vegetables.', timeMinutes: 35),
      CategoryDish(id: 'c-th-h3', name: 'Som Tam', description: 'Spicy green papaya salad.', timeMinutes: 20),
      CategoryDish(id: 'c-th-h4', name: 'Grilled Fish Thai', description: 'Herb-marinated grilled fish.', timeMinutes: 35),
      CategoryDish(id: 'c-th-h5', name: 'Stir-Fried Morning Glory', description: 'Quick leafy green stir-fry.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-th-d1', name: 'Pad Thai', description: 'Stir-fried noodles with tamarind.', timeMinutes: 30),
      CategoryDish(id: 'c-th-d2', name: 'Green Curry', description: 'Coconut curry with basil.', timeMinutes: 35),
      CategoryDish(id: 'c-th-d3', name: 'Massaman Curry', description: 'Mild peanut curry with potato.', timeMinutes: 40),
      CategoryDish(id: 'c-th-d4', name: 'Pad Krapow', description: 'Basil stir-fry with chilli.', timeMinutes: 25),
      CategoryDish(id: 'c-th-d5', name: 'Thai Red Curry', description: 'Spicy coconut curry with veg.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-th-v1', name: 'Veg Pad Thai', description: 'Classic noodles, meat-free.', timeMinutes: 30),
      CategoryDish(id: 'c-th-v2', name: 'Green Curry Veg', description: 'Vegetable green curry.', timeMinutes: 35),
      CategoryDish(id: 'c-th-v3', name: 'Thai Spring Rolls', description: 'Crisp rolls with dipping sauce.', timeMinutes: 30),
      CategoryDish(id: 'c-th-v4', name: 'Som Tam', description: 'Fresh spicy papaya salad.', timeMinutes: 20),
      CategoryDish(id: 'c-th-v5', name: 'Coconut Tofu Curry', description: 'Mild curry with tofu.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-th-n1', name: 'Pad Krapow Chicken', description: 'Basil chicken with fried egg.', timeMinutes: 25),
      CategoryDish(id: 'c-th-n2', name: 'Thai Red Curry Chicken', description: 'Chicken in spicy coconut curry.', timeMinutes: 35),
      CategoryDish(id: 'c-th-n3', name: 'Tom Yum Prawns', description: 'Hot-sour prawn soup.', timeMinutes: 25),
      CategoryDish(id: 'c-th-n4', name: 'Massaman Beef', description: 'Beef in a mellow peanut curry.', timeMinutes: 50),
      CategoryDish(id: 'c-th-n5', name: 'Thai Fish Cakes', description: 'Crisp spiced fish patties.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-th-s1', name: 'Mango Sticky Rice', description: 'Sweet rice with mango and coconut.', timeMinutes: 40),
      CategoryDish(id: 'c-th-s2', name: 'Thai Coconut Pancake', description: 'Soft coconut pancakes.', timeMinutes: 25),
      CategoryDish(id: 'c-th-s3', name: 'Banana in Coconut Milk', description: 'Warm banana coconut dessert.', timeMinutes: 20),
      CategoryDish(id: 'c-th-s4', name: 'Tub Tim Krob', description: 'Crisp water chestnuts in syrup.', timeMinutes: 30),
      CategoryDish(id: 'c-th-s5', name: 'Coconut Sticky Rice Balls', description: 'Balls of sweet coconut rice.', timeMinutes: 35),
    ],
    'kids': [
      CategoryDish(id: 'c-th-k1', name: 'Mango Sticky Rice', description: 'Sweet mango rice cup.', timeMinutes: 40),
      CategoryDish(id: 'c-th-k2', name: 'Veg Fried Rice Thai', description: 'Mild Thai-style fried rice.', timeMinutes: 25),
      CategoryDish(id: 'c-th-k3', name: 'Banana Coconut Bowl', description: 'Soft banana in coconut milk.', timeMinutes: 20),
      CategoryDish(id: 'c-th-k4', name: 'Chicken Satay', description: 'Mild peanut skewers.', timeMinutes: 35),
      CategoryDish(id: 'c-th-k5', name: 'Thai Pancake Bite', description: 'Sweet mini pancakes.', timeMinutes: 20),
    ],
  },
};
