import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart8 = {
  'himachali': {
    'breakfast': [
      CategoryDish(id: 'c-hm-b1', name: 'Chilra', description: 'Buckwheat pancakes with spices.', timeMinutes: 20),
      CategoryDish(id: 'c-hm-b2', name: 'Seera', description: 'Sweet wheat pudding.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-b3', name: 'Sidu Breakfast', description: 'Steamed wheat bread.', timeMinutes: 40),
      CategoryDish(id: 'c-hm-b4', name: 'Babru', description: 'Black gram stuffed fried bread.', timeMinutes: 35),
      CategoryDish(id: 'c-hm-b5', name: 'Bedvin Toast', description: 'Local style spiced toast.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-hm-h1', name: 'Khaardi', description: 'Light garlic and sesame curry.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-h2', name: 'Pachhadi', description: 'Curd chutney with local herbs.', timeMinutes: 20),
      CategoryDish(id: 'c-hm-h3', name: 'Vegetable Sidu', description: 'Steamed bread with greens.', timeMinutes: 40),
      CategoryDish(id: 'c-hm-h4', name: 'Lassi Himachali', description: 'Cooling buttermilk.', timeMinutes: 10),
      CategoryDish(id: 'c-hm-h5', name: 'Seasonal Tarkari', description: 'Simple mountain vegetable curry.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-hm-d1', name: 'Dham Thali', description: 'Festive lentil and rice feast.', timeMinutes: 60),
      CategoryDish(id: 'c-hm-d2', name: 'Madra', description: 'Chickpea curry with yogurt.', timeMinutes: 45),
      CategoryDish(id: 'c-hm-d3', name: 'Chana Madra', description: 'Creamy chickpea curry.', timeMinutes: 45),
      CategoryDish(id: 'c-hm-d4', name: 'Sepu Vadi', description: 'Spinach lentil dumplings.', timeMinutes: 50),
      CategoryDish(id: 'c-hm-d5', name: 'Makki Roti with Sarson', description: 'Corn bread with mustard greens.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-hm-v1', name: 'Madra', description: 'Yogurt-chickpea curry.', timeMinutes: 45),
      CategoryDish(id: 'c-hm-v2', name: 'Pachhadi', description: 'Herby curd chutney.', timeMinutes: 20),
      CategoryDish(id: 'c-hm-v3', name: 'Sepu Vadi', description: 'Lentil and spinach dumplings.', timeMinutes: 50),
      CategoryDish(id: 'c-hm-v4', name: 'Kaddu Kya Chaa', description: 'Pumpkin curry.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-v5', name: 'Aloo Siddu', description: 'Potato-stuffed steamed bread.', timeMinutes: 40),
    ],
    'nonveg': [
      CategoryDish(id: 'c-hm-n1', name: 'Chicken Madra', description: 'Chicken in a yogurt curry.', timeMinutes: 50),
      CategoryDish(id: 'c-hm-n2', name: 'Rajasthani-Style Chicken', description: 'Rustic mountain chicken curry.', timeMinutes: 55),
      CategoryDish(id: 'c-hm-n3', name: 'Fish Himachali', description: 'River fish in spices.', timeMinutes: 35),
      CategoryDish(id: 'c-hm-n4', name: 'Egg Curry Himachali', description: 'Eggs in onion-tomato gravy.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-n5', name: 'Mutton Handi', description: 'Slow-cooked mutton.', timeMinutes: 85),
    ],
    'sweet': [
      CategoryDish(id: 'c-hm-s1', name: 'Patande', description: 'Sweet pancakes with khoya.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-s2', name: 'Sheera', description: 'Semolina halwa with nuts.', timeMinutes: 25),
      CategoryDish(id: 'c-hm-s3', name: 'Siddu Sweet', description: 'Sweet stuffed steamed bread.', timeMinutes: 40),
      CategoryDish(id: 'c-hm-s4', name: 'Kheer Himachali', description: 'Rice pudding with cardamom.', timeMinutes: 40),
      CategoryDish(id: 'c-hm-s5', name: 'Bair Pinnie', description: 'Ber fruit sweet balls.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-hm-k1', name: 'Chilra Bite', description: 'Small buckwheat pancakes.', timeMinutes: 20),
      CategoryDish(id: 'c-hm-k2', name: 'Patande Roll', description: 'Sweet pancake rolls.', timeMinutes: 30),
      CategoryDish(id: 'c-hm-k3', name: 'Sheera Cup', description: 'Small halwa cup.', timeMinutes: 25),
      CategoryDish(id: 'c-hm-k4', name: 'Sweet Lassi', description: 'Sweetened yogurt drink.', timeMinutes: 10),
      CategoryDish(id: 'c-hm-k5', name: 'Sidu with Butter', description: 'Soft bread with butter.', timeMinutes: 40),
    ],
  },
  'uttarakhandi': {
    'breakfast': [
      CategoryDish(id: 'c-ut-b1', name: 'Aloo Ke Gutke', description: 'Spiced mountain potato stir-fry.', timeMinutes: 20),
      CategoryDish(id: 'c-ut-b2', name: 'Jhangora Ki Kheer', description: 'Millet porridge with jaggery.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-b3', name: 'Gahat Dal Paratha', description: 'Horse-gram dal paratha.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-b4', name: 'Bal Mithai Toast', description: 'Sweet local chocolate toast.', timeMinutes: 15),
      CategoryDish(id: 'c-ut-b5', name: 'Mandua Roti Breakfast', description: 'Finger-millet flatbread.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-ut-h1', name: 'Gahat Dal', description: 'Protein-rich horse gram soup.', timeMinutes: 50),
      CategoryDish(id: 'c-ut-h2', name: 'Kandalee Ka Saag', description: 'Stinging nettle greens.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-h3', name: 'Chainsoo Light', description: 'Urad dal gravy, light.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-h4', name: 'Jhangora Pulao', description: 'Barnyard millet pilaf.', timeMinutes: 30),
      CategoryDish(id: 'c-ut-h5', name: 'Mung Dal Ka Paani', description: 'Thin warming dal soup.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-ut-d1', name: 'Bhatt Ki Churkani', description: 'Black bean curry.', timeMinutes: 50),
      CategoryDish(id: 'c-ut-d2', name: 'Chainsoo', description: 'Urad dal with garlic.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-d3', name: 'Kafuli', description: 'Spinach and fenugreek curry.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-d4', name: 'Thechwani', description: 'Spicy potato-garlic mash.', timeMinutes: 25),
      CategoryDish(id: 'c-ut-d5', name: 'Rote', description: 'Rice-flour flatbread with curry.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-ut-v1', name: 'Kafuli', description: 'Leafy greens curry.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-v2', name: 'Aloo Ke Gutke', description: 'Tempered potatoes.', timeMinutes: 20),
      CategoryDish(id: 'c-ut-v3', name: 'Bhatt Ki Churkani', description: 'Black soybean curry.', timeMinutes: 50),
      CategoryDish(id: 'c-ut-v4', name: 'Kandalee Saag', description: 'Nettle greens with spices.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-v5', name: 'Rasa', description: 'Simple lentil gravy.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ut-n1', name: 'Chicken Thechwani', description: 'Spicy pahadi chicken.', timeMinutes: 50),
      CategoryDish(id: 'c-ut-n2', name: 'Fish Uttarakhandi', description: 'River fish with local spices.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-n3', name: 'Mutton Bhatt Curry', description: 'Mutton with black beans.', timeMinutes: 90),
      CategoryDish(id: 'c-ut-n4', name: 'Egg Masala Pahadi', description: 'Mountain-style egg curry.', timeMinutes: 30),
      CategoryDish(id: 'c-ut-n5', name: 'Chicken Ka Paani', description: 'Thin spicy chicken broth.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-ut-s1', name: 'Bal Mithai', description: 'Chocolate fudge with sugar pearls.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-s2', name: 'Jhangora Kheer', description: 'Millet pudding with jaggery.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-s3', name: 'Singodi', description: 'Coconut wrapped sweet.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-s4', name: 'Sungtani', description: 'Jaggery rice sweet.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-s5', name: 'Arsa', description: 'Crisp rice-flour sweets.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-ut-k1', name: 'Bal Mithai Bite', description: 'Small chocolate fudge piece.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-k2', name: 'Jhangora Kheer Cup', description: 'Sweet millet pudding.', timeMinutes: 35),
      CategoryDish(id: 'c-ut-k3', name: 'Aloo Gutke Bowl', description: 'Mild potato bites.', timeMinutes: 20),
      CategoryDish(id: 'c-ut-k4', name: 'Singodi Bite', description: 'Sweet coconut parcel.', timeMinutes: 40),
      CategoryDish(id: 'c-ut-k5', name: 'Roté with Curd', description: 'Soft flatbread with curd.', timeMinutes: 30),
    ],
  },
  'parsi': {
    'breakfast': [
      CategoryDish(id: 'c-pa-b1', name: 'Akuri', description: 'Spiced scrambled eggs, creamy.', timeMinutes: 15),
      CategoryDish(id: 'c-pa-b2', name: 'Pao Bhaji', description: 'Spiced mash with buttered bread.', timeMinutes: 35),
      CategoryDish(id: 'c-pa-b3', name: 'Bun Maskaa Chai', description: 'Buttered bun with tea.', timeMinutes: 10),
      CategoryDish(id: 'c-pa-b4', name: 'Nankhatai Breakfast', description: 'Buttery shortbread cookies.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-b5', name: 'Parsi Omelette', description: 'Herby spiced omelette.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-pa-h1', name: 'Dhansak Light', description: 'Lentil stew with meat or veg.', timeMinutes: 60),
      CategoryDish(id: 'c-pa-h2', name: 'Mung Dal Parsi', description: 'Simple moong dal.', timeMinutes: 35),
      CategoryDish(id: 'c-pa-h3', name: 'Saria Chicken Soup', description: 'Light chicken broth.', timeMinutes: 40),
      CategoryDish(id: 'c-pa-h4', name: 'Papeta Nu Shaak', description: 'Light potato curry.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-h5', name: 'Salad Parsi', description: 'Fresh cucumber-onion salad.', timeMinutes: 10),
    ],
    'dinner': [
      CategoryDish(id: 'c-pa-d1', name: 'Dhansak', description: 'Lentil and meat stew with caramelised rice.', timeMinutes: 75),
      CategoryDish(id: 'c-pa-d2', name: 'Sali Boti', description: 'Lamb curry with crisp potato straws.', timeMinutes: 70),
      CategoryDish(id: 'c-pa-d3', name: 'Patra ni Machhi', description: 'Fish steamed in chutney and leaf.', timeMinutes: 45),
      CategoryDish(id: 'c-pa-d4', name: 'Lagaan Nu Custard', description: 'Savoury egg custard bake.', timeMinutes: 50),
      CategoryDish(id: 'c-pa-d5', name: 'Chicken Farcha', description: 'Crisp spiced fried chicken.', timeMinutes: 45),
    ],
    'veg': [
      CategoryDish(id: 'c-pa-v1', name: 'Sakka', description: 'Leafy vegetable curry.', timeMinutes: 35),
      CategoryDish(id: 'c-pa-v2', name: 'Dhansak Veg', description: 'Vegetable lentil stew.', timeMinutes: 60),
      CategoryDish(id: 'c-pa-v3', name: 'Papeta Nu Shaak', description: 'Sweet potato curry.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-v4', name: 'Bhindi Parsi', description: 'Okra with jaggery and tamarind.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-v5', name: 'Lentil Rice Parsi', description: 'Dal and rice, Parsi style.', timeMinutes: 40),
    ],
    'nonveg': [
      CategoryDish(id: 'c-pa-n1', name: 'Sali Boti', description: 'Rich lamb curry.', timeMinutes: 70),
      CategoryDish(id: 'c-pa-n2', name: 'Patra ni Machhi', description: 'Banana-leaf steamed fish.', timeMinutes: 45),
      CategoryDish(id: 'c-pa-n3', name: 'Chicken Farcha', description: 'Crisp golden chicken.', timeMinutes: 45),
      CategoryDish(id: 'c-pa-n4', name: 'Dhansak', description: 'The classic Parsi staple.', timeMinutes: 75),
      CategoryDish(id: 'c-pa-n5', name: 'Egg Curry Parsi', description: 'Eggs in a tangy gravy.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-pa-s1', name: 'Lagaan Nu Sweet', description: 'Caramelised custard bake.', timeMinutes: 50),
      CategoryDish(id: 'c-pa-s2', name: 'Nankhatai', description: 'Melt-in-mouth cookies.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-s3', name: 'Kulfi Parsi', description: 'Cardamom kulfi.', timeMinutes: 40),
      CategoryDish(id: 'c-pa-s4', name: 'Mava Cake', description: 'Rich milk cake.', timeMinutes: 45),
      CategoryDish(id: 'c-pa-s5', name: 'Sev with Jaggery', description: 'Sweet vermicelli treat.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-pa-k1', name: 'Pao Bhaji Bite', description: 'Small bhaji with bread.', timeMinutes: 35),
      CategoryDish(id: 'c-pa-k2', name: 'Akuri Toast', description: 'Soft spiced eggs on toast.', timeMinutes: 15),
      CategoryDish(id: 'c-pa-k3', name: 'Nankhatai', description: 'Buttery cookies.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-k4', name: 'Sweet Custard Cup', description: 'Vanilla custard.', timeMinutes: 30),
      CategoryDish(id: 'c-pa-k5', name: 'Kulfi Stick', description: 'Cold sweet kulfi.', timeMinutes: 30),
    ],
  },
  'vietnamese': {
    'breakfast': [
      CategoryDish(id: 'c-vi-b1', name: 'Pho', description: 'Fragrant noodle soup with herbs.', timeMinutes: 50),
      CategoryDish(id: 'c-vi-b2', name: 'Banh Mi Breakfast', description: 'Crisp baguette with fillings.', timeMinutes: 20),
      CategoryDish(id: 'c-vi-b3', name: 'Xoi', description: 'Sticky rice with toppings.', timeMinutes: 30),
      CategoryDish(id: 'c-vi-b4', name: 'Vietnamese Egg Coffee', description: 'Rich coffee with egg cream.', timeMinutes: 15),
      CategoryDish(id: 'c-vi-b5', name: 'Banh Cuon', description: 'Steamed rice rolls with filling.', timeMinutes: 45),
    ],
    'healthy': [
      CategoryDish(id: 'c-vi-h1', name: 'Goi Cuon', description: 'Fresh summer rolls with prawn.', timeMinutes: 30),
      CategoryDish(id: 'c-vi-h2', name: 'Pho Ga Light', description: 'Light chicken noodle soup.', timeMinutes: 50),
      CategoryDish(id: 'c-vi-h3', name: 'Vietnamese Salad', description: 'Herby green papaya salad.', timeMinutes: 20),
      CategoryDish(id: 'c-vi-h4', name: 'Steamed Fish Vietnamese', description: 'Fish with ginger and soy.', timeMinutes: 25),
      CategoryDish(id: 'c-vi-h5', name: 'Morning Glory Stir-Fry', description: 'Garlic greens, quick and light.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-vi-d1', name: 'Pho Bo', description: 'Beef noodle soup, deep and clear.', timeMinutes: 60),
      CategoryDish(id: 'c-vi-d2', name: 'Banh Xeo', description: 'Crisp turmeric pancake.', timeMinutes: 40),
      CategoryDish(id: 'c-vi-d3', name: 'Bun Cha', description: 'Grilled pork with rice noodles.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-d4', name: 'Com Tam', description: 'Broken rice with grilled pork.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-d5', name: 'Coconut Prawn Curry', description: 'Prawns in fragrant coconut curry.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-vi-v1', name: 'Tofu in Tomato Sauce', description: 'Soft tofu, home-style.', timeMinutes: 25),
      CategoryDish(id: 'c-vi-v2', name: 'Veg Pho', description: 'Vegetable noodle soup.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-v3', name: 'Banh Xeo Veg', description: 'Vegetable crisp pancake.', timeMinutes: 40),
      CategoryDish(id: 'c-vi-v4', name: 'Mushroom Stir-Fry', description: 'Garlic mushroom dish.', timeMinutes: 20),
      CategoryDish(id: 'c-vi-v5', name: 'Green Papaya Salad', description: 'Crunchy herby salad.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-vi-n1', name: 'Pho Bo', description: 'Classic beef pho.', timeMinutes: 60),
      CategoryDish(id: 'c-vi-n2', name: 'Bun Cha', description: 'Char-grilled pork with noodles.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-n3', name: 'Grilled Lemongrass Chicken', description: 'Citrusy char-grilled chicken.', timeMinutes: 40),
      CategoryDish(id: 'c-vi-n4', name: 'Prawn Spring Rolls', description: 'Crisp fried prawn rolls.', timeMinutes: 35),
      CategoryDish(id: 'c-vi-n5', name: 'Shaking Beef', description: 'Caramelised seared beef.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-vi-s1', name: 'Chè Ba Màu', description: 'Three-colour layered dessert.', timeMinutes: 40),
      CategoryDish(id: 'c-vi-s2', name: 'Bánh Flan', description: 'Vietnamese crème caramel.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-s3', name: 'Coconut Sticky Rice', description: 'Sweet rice with coconut cream.', timeMinutes: 35),
      CategoryDish(id: 'c-vi-s4', name: 'Mango Sticky Rice Viet', description: 'Mango with sweet sticky rice.', timeMinutes: 40),
      CategoryDish(id: 'c-vi-s5', name: 'Bánh Chuối', description: 'Banana and coconut cake.', timeMinutes: 50),
    ],
    'kids': [
      CategoryDish(id: 'c-vi-k1', name: 'Summer Roll Bite', description: 'Small fresh rice rolls.', timeMinutes: 30),
      CategoryDish(id: 'c-vi-k2', name: 'Pho Bowl', description: 'Mild noodle soup.', timeMinutes: 50),
      CategoryDish(id: 'c-vi-k3', name: 'Sticky Rice Cup', description: 'Sweet sticky rice.', timeMinutes: 30),
      CategoryDish(id: 'c-vi-k4', name: 'Banh Flan Cup', description: 'Small caramel custard.', timeMinutes: 45),
      CategoryDish(id: 'c-vi-k5', name: 'Grilled Chicken Bite', description: 'Small sweet chicken pieces.', timeMinutes: 35),
    ],
  },
};
