import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart2 = {
  'gujarati': {
    'breakfast': [
      CategoryDish(id: 'c-gu-b1', name: 'Thepla', description: 'Methi flatbread, perfect with chai.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-b2', name: 'Khakhra', description: 'Crisp spiced roasted flatbread.', timeMinutes: 25),
      CategoryDish(id: 'c-gu-b3', name: 'Fafda with Chutney', description: 'Gram-flour strips with green chilli chutney.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-b4', name: 'Muthiya', description: 'Steamed fenugreek dumplings, pan-fried.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-b5', name: 'Gathiya', description: 'Crunchy besan savoury breakfast snack.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-gu-h1', name: 'Moong Dal Dhokla', description: 'Steamed mung bean cakes, light and airy.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-h2', name: 'Khichdi Kadhi', description: 'Gujarati khichdi with yogurt curry.', timeMinutes: 40),
      CategoryDish(id: 'c-gu-h3', name: 'Lauki Chana Dal', description: 'Bottle gourd with split chickpeas.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-h4', name: 'Oats Thepla', description: 'Oat flatbread with herbs, low oil.', timeMinutes: 25),
      CategoryDish(id: 'c-gu-h5', name: 'Mixed Veg Undhiyu-light', description: 'A lighter steamed mixed vegetable dish.', timeMinutes: 35),
    ],
    'dinner': [
      CategoryDish(id: 'c-gu-d1', name: 'Undhiyu', description: 'Winter root vegetables with green chutney and dumplings.', timeMinutes: 60),
      CategoryDish(id: 'c-gu-d2', name: 'Dal Dhokli', description: 'Lentil soup with whole-wheat noodle pieces.', timeMinutes: 45),
      CategoryDish(id: 'c-gu-d3', name: 'Ringan no Olo', description: 'Spicy-sweet eggplant curry.', timeMinutes: 40),
      CategoryDish(id: 'c-gu-d4', name: 'Gujarati Kadhi', description: 'Sweet-sour yogurt curry with pakoras.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-d5', name: 'Bajra Rotla', description: 'Pearl millet flatbread with garlic chutney.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-gu-v1', name: 'Undhiyu', description: 'Rich winter vegetable medley with spices.', timeMinutes: 60),
      CategoryDish(id: 'c-gu-v2', name: 'Rasawala Bataka', description: 'Potatoes in a thin peanut-tamarind gravy.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-v3', name: 'Sev Tameta', description: 'Tomato curry topped with crispy sev.', timeMinutes: 25),
      CategoryDish(id: 'c-gu-v4', name: 'Gujarati Sukhi Bhaji', description: 'Dry mixed vegetable with coconut.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-v5', name: 'Methi Muthiya', description: 'Fenugreek dumplings in a tangy sauce.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-gu-n1', name: 'Gujarati Chicken Curry', description: 'Chicken with a hint of jaggery and lemon.', timeMinutes: 55),
      CategoryDish(id: 'c-gu-n2', name: 'Mutton Khichdi', description: 'Meat and rice cooked with warm spices.', timeMinutes: 60),
      CategoryDish(id: 'c-gu-n3', name: 'Fish in Coconut Curry', description: 'Coastal fish with coconut and curry leaves.', timeMinutes: 40),
      CategoryDish(id: 'c-gu-n4', name: 'Egg Khichdi', description: 'Rice with eggs and gentle spices.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-n5', name: 'Chicken Dhokla-style', description: 'Steamed spiced chicken cakes.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-gu-s1', name: 'Mohanthal', description: 'Besan and ghee fudge with nuts.', timeMinutes: 45),
      CategoryDish(id: 'c-gu-s2', name: 'Churma Ladoo', description: 'Sweet flour dumplings in ghee and jaggery.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-s3', name: 'Basundi', description: 'Thick sweetened milk with cardamom.', timeMinutes: 50),
      CategoryDish(id: 'c-gu-s4', name: 'Shrikhand', description: 'Hung curd whipped with saffron.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-s5', name: 'Gud Papdi', description: 'Jaggery and wheat brittle squares.', timeMinutes: 25),
    ],
    'kids': [
      CategoryDish(id: 'c-gu-k1', name: 'Mini Khakhra', description: 'Crisp thin flatbread kids crunch on.', timeMinutes: 25),
      CategoryDish(id: 'c-gu-k2', name: 'Sweet Dhokla', description: 'Soft steamed cakes, mildly sweet.', timeMinutes: 35),
      CategoryDish(id: 'c-gu-k3', name: 'Gathiya Bites', description: 'Crunchy gram-flour sticks with chai.', timeMinutes: 30),
      CategoryDish(id: 'c-gu-k4', name: 'Banana Handvo', description: 'Baked savoury cake with banana and rice.', timeMinutes: 45),
      CategoryDish(id: 'c-gu-k5', name: 'Curd Rice', description: 'Comforting yogurt rice with pomegranate.', timeMinutes: 15),
    ],
  },
  'rajasthani': {
    'breakfast': [
      CategoryDish(id: 'c-rj-b1', name: 'Dal Baati Breakfast', description: 'Ghee-soaked baati with dal and churma.', timeMinutes: 45),
      CategoryDish(id: 'c-rj-b2', name: 'Bajra Roti with Lehsun Chutney', description: 'Millet flatbread with garlic chutney.', timeMinutes: 35),
      CategoryDish(id: 'c-rj-b3', name: 'Pyaaz Kachori', description: 'Crisp pastry stuffed with spiced onion.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-b4', name: 'Besan Chilla', description: 'Gram-flour pancakes with herbs.', timeMinutes: 20),
      CategoryDish(id: 'c-rj-b5', name: 'Ghewar Breakfast', description: 'Honeycomb sweet with rabri, festive.', timeMinutes: 40),
    ],
    'healthy': [
      CategoryDish(id: 'c-rj-h1', name: 'Bajra Khichdi', description: 'Millet porridge with moong dal.', timeMinutes: 35),
      CategoryDish(id: 'c-rj-h2', name: 'Ker Sangri', description: 'Desert beans and berries, light on oil.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-h3', name: 'Gatte Palak', description: 'Gram dumplings in spinach, simmered.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-h4', name: 'Moong Dal Halwa-light', description: 'A lighter moong dal porridge.', timeMinutes: 30),
      CategoryDish(id: 'c-rj-h5', name: 'Sprout Khichdi', description: 'Sprouted moong with millet rice.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-rj-d1', name: 'Dal Baati Churma', description: 'The classic Rajasthani thali staple.', timeMinutes: 70),
      CategoryDish(id: 'c-rj-d2', name: 'Gatte ki Sabzi', description: 'Gram-flour dumplings in yogurt gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-rj-d3', name: 'Panchmel Dal', description: 'Five lentil mix with rich tempering.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-d4', name: 'Safed Maas', description: 'White mutton curry with cashews.', timeMinutes: 85),
      CategoryDish(id: 'c-rj-d5', name: 'Papad ki Sabzi', description: 'Crumbled papad in a spicy yogurt gravy.', timeMinutes: 30),
    ],
    'veg': [
      CategoryDish(id: 'c-rj-v1', name: 'Ker Sangri', description: 'Desert berry and bean curry.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-v2', name: 'Gatte ki Sabzi', description: 'Yogurt gravy with gram-flour dumplings.', timeMinutes: 50),
      CategoryDish(id: 'c-rj-v3', name: 'Baati', description: 'Ghee-roasted wheat balls served with dal.', timeMinutes: 45),
      CategoryDish(id: 'c-rj-v4', name: 'Aaloo Pyaaz Sabzi', description: 'Dry potato and onion curry.', timeMinutes: 25),
      CategoryDish(id: 'c-rj-v5', name: 'Haldi Sabzi', description: 'Turmeric-root and vegetable curry.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-rj-n1', name: 'Lal Maas', description: 'Fiery mutton curry with Mathania chillies.', timeMinutes: 90),
      CategoryDish(id: 'c-rj-n2', name: 'Safed Maas', description: 'Creamy white mutton with cardamom.', timeMinutes: 85),
      CategoryDish(id: 'c-rj-n3', name: 'Junglee Maas', description: 'Wild-style mutton with minimal spice.', timeMinutes: 80),
      CategoryDish(id: 'c-rj-n4', name: 'Mohan Maas', description: 'Mutton in saffron and ghee-rich gravy.', timeMinutes: 90),
      CategoryDish(id: 'c-rj-n5', name: 'Laal Chicken', description: 'Chicken in a red chilli-spiced gravy.', timeMinutes: 60),
    ],
    'sweet': [
      CategoryDish(id: 'c-rj-s1', name: 'Ghevar', description: 'Honeycomb fried sweet soaked in syrup.', timeMinutes: 60),
      CategoryDish(id: 'c-rj-s2', name: 'Churma', description: 'Sweet crushed wheat with ghee and jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-s3', name: 'Gud Pachkuta', description: 'Jaggery and seed sweet mix.', timeMinutes: 25),
      CategoryDish(id: 'c-rj-s4', name: 'Malpua', description: 'Fried pancakes in cardamom syrup.', timeMinutes: 30),
      CategoryDish(id: 'c-rj-s5', name: 'Dil Khushal', description: 'Crunchy-sweet sesame and jaggery bar.', timeMinutes: 25),
    ],
    'kids': [
      CategoryDish(id: 'c-rj-k1', name: 'Mini Baati', description: 'Small ghee baatis with a sweet dip.', timeMinutes: 40),
      CategoryDish(id: 'c-rj-k2', name: 'Churma Ladoo', description: 'Sweet flour balls with nuts.', timeMinutes: 35),
      CategoryDish(id: 'c-rj-k3', name: 'Milk Ghewar Bite', description: 'Small ghewar pieces with rabri.', timeMinutes: 45),
      CategoryDish(id: 'c-rj-k4', name: 'Besan Ladoo', description: 'Roasted gram-flour sweet balls.', timeMinutes: 30),
      CategoryDish(id: 'c-rj-k5', name: 'Sweet Bajra Porridge', description: 'Millet porridge with jaggery and ghee.', timeMinutes: 25),
    ],
  },
  'punjabi': {
    'breakfast': [
      CategoryDish(id: 'c-pj-b1', name: 'Aloo Paratha with Dahi', description: 'Potato-stuffed paratha with butter and curd.', timeMinutes: 40),
      CategoryDish(id: 'c-pj-b2', name: 'Chole Bhature', description: 'Spiced chickpeas with puffed bread.', timeMinutes: 50),
      CategoryDish(id: 'c-pj-b3', name: 'Poha Amritsari', description: 'Flattened rice with peanuts and lemon.', timeMinutes: 20),
      CategoryDish(id: 'c-pj-b4', name: 'Makki Roti Breakfast', description: 'Corn flatbread with white butter.', timeMinutes: 35),
      CategoryDish(id: 'c-pj-b5', name: 'Chana Kulcha', description: 'Chickpea curry with baked flatbread.', timeMinutes: 45),
    ],
    'healthy': [
      CategoryDish(id: 'c-pj-h1', name: 'Moong Dal Khichdi', description: 'Mung lentil rice, light and comforting.', timeMinutes: 30),
      CategoryDish(id: 'c-pj-h2', name: 'Sarson ka Saag-light', description: 'Mustard greens, made lighter.', timeMinutes: 45),
      CategoryDish(id: 'c-pj-h3', name: 'Paneer Bhurji-less-oil', description: 'Scrambled paneer with herbs.', timeMinutes: 20),
      CategoryDish(id: 'c-pj-h4', name: 'Masoor Dal', description: 'Red lentil dal with garlic tadka.', timeMinutes: 30),
      CategoryDish(id: 'c-pj-h5', name: 'Vegetable Pulao', description: 'Light basmati rice with vegetables.', timeMinutes: 35),
    ],
    'dinner': [
      CategoryDish(id: 'c-pj-d1', name: 'Dal Makhani', description: 'Slow-simmered black lentils with cream.', timeMinutes: 60),
      CategoryDish(id: 'c-pj-d2', name: 'Paneer Butter Masala', description: 'Paneer in a rich tomato-butter gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-pj-d3', name: 'Rajma Chawal', description: 'Kidney beans in Punjabi masala with rice.', timeMinutes: 50),
      CategoryDish(id: 'c-pj-d4', name: 'Chole Masala', description: 'Chickpeas with onion-tomato masala.', timeMinutes: 45),
      CategoryDish(id: 'c-pj-d5', name: 'Sarso da Saag', description: 'Mustard greens with makki roti.', timeMinutes: 50),
    ],
    'veg': [
      CategoryDish(id: 'c-pj-v1', name: 'Chole Masala', description: 'Chickpeas simmered in Punjabi spices.', timeMinutes: 45),
      CategoryDish(id: 'c-pj-v2', name: 'Sarson da Saag', description: 'Mustard greens mash with butter.', timeMinutes: 50),
      CategoryDish(id: 'c-pj-v3', name: 'Baingan Bharta', description: 'Smoky roasted eggplant mash.', timeMinutes: 40),
      CategoryDish(id: 'c-pj-v4', name: 'Rajma', description: 'Kidney beans in a rich onion gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-pj-v5', name: 'Gobi Matar', description: 'Cauliflower and peas in a dry curry.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-pj-n1', name: 'Butter Chicken', description: 'Tandoori-style chicken in a makhani sauce.', timeMinutes: 60),
      CategoryDish(id: 'c-pj-n2', name: 'Amritsari Fish', description: 'Crisp batter-fried river fish.', timeMinutes: 35),
      CategoryDish(id: 'c-pj-n3', name: 'Tandoori Chicken', description: 'Char-grilled chicken with yogurt marinade.', timeMinutes: 50),
      CategoryDish(id: 'c-pj-n4', name: 'Mutton Rogan Josh', description: 'Kashmiri-spiced mutton curry.', timeMinutes: 90),
      CategoryDish(id: 'c-pj-n5', name: 'Egg Bhurji', description: 'Spiced scrambled eggs with roti.', timeMinutes: 20),
    ],
    'sweet': [
      CategoryDish(id: 'c-pj-s1', name: 'Gajar ka Halwa', description: 'Slow-cooked carrot pudding with ghee.', timeMinutes: 45),
      CategoryDish(id: 'c-pj-s2', name: 'Kheer', description: 'Creamy rice pudding with cardamom.', timeMinutes: 40),
      CategoryDish(id: 'c-pj-s3', name: 'Phirni', description: 'Ground rice pudding in earthen bowls.', timeMinutes: 40),
      CategoryDish(id: 'c-pj-s4', name: 'Pinni', description: 'Whole-wheat and ghee sweet balls.', timeMinutes: 35),
      CategoryDish(id: 'c-pj-s5', name: 'Lassi Sweet', description: 'Chilled yogurt drink with cream.', timeMinutes: 10),
    ],
    'kids': [
      CategoryDish(id: 'c-pj-k1', name: 'Mini Paneer Paratha', description: 'Small cheese-stuffed parathas.', timeMinutes: 30),
      CategoryDish(id: 'c-pj-k2', name: 'Sweet Lassi', description: 'Creamy yogurt drink, mild and sweet.', timeMinutes: 10),
      CategoryDish(id: 'c-pj-k3', name: 'Bhatura Bites', description: 'Puffed bread torn into kid-friendly pieces.', timeMinutes: 35),
      CategoryDish(id: 'c-pj-k4', name: 'Corn Chaat', description: 'Sweet corn with butter and lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-pj-k5', name: 'Gajar Halwa Cup', description: 'Carrot pudding in a little cup.', timeMinutes: 40),
    ],
  },
  'haryanvi': {
    'breakfast': [
      CategoryDish(id: 'c-hy-b1', name: 'Bajra Khichdi', description: 'Pearl millet porridge with moong dal.', timeMinutes: 35),
      CategoryDish(id: 'c-hy-b2', name: 'Bajra Roti Breakfast', description: 'Millet flatbread with white butter.', timeMinutes: 35),
      CategoryDish(id: 'c-hy-b3', name: 'Bathua Paratha', description: 'Goosefoot greens stuffed paratha.', timeMinutes: 35),
      CategoryDish(id: 'c-hy-b4', name: 'Besan Chilla', description: 'Gram-flour pancakes with onion.', timeMinutes: 20),
      CategoryDish(id: 'c-hy-b5', name: 'Kadhi Chawal Breakfast', description: 'Yogurt curry with steamed rice.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-hy-h1', name: 'Bathua Raita', description: 'Greens mixed in whisked yogurt.', timeMinutes: 15),
      CategoryDish(id: 'c-hy-h2', name: 'Moong Dal Soup', description: 'Thin mung dal broth with cumin.', timeMinutes: 25),
      CategoryDish(id: 'c-hy-h3', name: 'Lauki Chana', description: 'Bottle gourd with chickpeas.', timeMinutes: 30),
      CategoryDish(id: 'c-hy-h4', name: 'Mixed Sprout Salad', description: 'Sprouted beans with lemon and herbs.', timeMinutes: 15),
      CategoryDish(id: 'c-hy-h5', name: 'Karela Sabzi', description: 'Bitter gourd cooked with less oil.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-hy-d1', name: 'Bajra Khichdi with Butter', description: 'Millet rice with moong dal and ghee.', timeMinutes: 35),
      CategoryDish(id: 'c-hy-d2', name: 'Hara Bhara Kebab', description: 'Spinach and pea patties.', timeMinutes: 35),
      CategoryDish(id: 'c-hy-d3', name: 'Methi Malai Paneer', description: 'Fenugreek paneer in cream gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-hy-d4', name: 'Kadhi Pakoda', description: 'Yogurt curry with fried dumplings.', timeMinutes: 45),
      CategoryDish(id: 'c-hy-d5', name: 'Chana Dal Khichdi', description: 'Chana dal with rice and spices.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-hy-v1', name: 'Bathua Raita', description: 'Greens and yogurt side.', timeMinutes: 15),
      CategoryDish(id: 'c-hy-v2', name: 'Kadhi', description: 'Tangy yogurt curry with gram dumplings.', timeMinutes: 45),
      CategoryDish(id: 'c-hy-v3', name: 'Aloo Tamatar', description: 'Potato and tomato curry.', timeMinutes: 30),
      CategoryDish(id: 'c-hy-v4', name: 'Sarson Ka Saag', description: 'Mustard greens with makki roti.', timeMinutes: 50),
      CategoryDish(id: 'c-hy-v5', name: 'Mixed Veg Raita', description: 'Boondi and vegetable raita.', timeMinutes: 15),
    ],
    'nonveg': [
      CategoryDish(id: 'c-hy-n1', name: 'Chicken Kadhai', description: 'Chicken with bell peppers and spices.', timeMinutes: 50),
      CategoryDish(id: 'c-hy-n2', name: 'Haryanvi Mutton', description: 'Mutton with whole spices and yogurt.', timeMinutes: 85),
      CategoryDish(id: 'c-hy-n3', name: 'Bhuna Chicken', description: 'Dry-style chicken with onion masala.', timeMinutes: 50),
      CategoryDish(id: 'c-hy-n4', name: 'Egg Curry', description: 'Boiled eggs in a rustic gravy.', timeMinutes: 30),
      CategoryDish(id: 'c-hy-n5', name: 'Fish Fry', description: 'Marinated fish, pan-fried crisp.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-hy-s1', name: 'Rabri', description: 'Thickened sweetened milk with nuts.', timeMinutes: 55),
      CategoryDish(id: 'c-hy-s2', name: 'Gur Chana', description: 'Jaggery with roasted chickpeas.', timeMinutes: 10),
      CategoryDish(id: 'c-hy-s3', name: 'Halwa', description: 'Sooji halwa with ghee and nuts.', timeMinutes: 25),
      CategoryDish(id: 'c-hy-s4', name: 'Kheer', description: 'Rice pudding with jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-hy-s5', name: 'Panjiri', description: 'Wheat-ghee sweet with dry fruits.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-hy-k1', name: 'Sweet Bajra Porridge', description: 'Millet porridge with jaggery.', timeMinutes: 25),
      CategoryDish(id: 'c-hy-k2', name: 'Besan Chilla Bites', description: 'Small gram pancakes with ketchup.', timeMinutes: 20),
      CategoryDish(id: 'c-hy-k3', name: 'Kadhi Chawal Bowl', description: 'Mild yogurt curry with rice.', timeMinutes: 30),
      CategoryDish(id: 'c-hy-k4', name: 'Gur Roti', description: 'Flatbread with jaggery inside.', timeMinutes: 30),
      CategoryDish(id: 'c-hy-k5', name: 'Roasted Chana Mix', description: 'Crunchy roasted chickpeas with jaggery.', timeMinutes: 10),
    ],
  },
  'kashmiri': {
    'breakfast': [
      CategoryDish(id: 'c-ks-b1', name: 'Noon Chai with Kulcha', description: 'Salty pink tea with hot kulcha bread.', timeMinutes: 25),
      CategoryDish(id: 'c-ks-b2', name: 'Kashmiri Kahwa', description: 'Saffron green tea with almonds.', timeMinutes: 20),
      CategoryDish(id: 'c-ks-b3', name: 'Girda', description: 'Soft buns with a crispy top, from the tandoor.', timeMinutes: 35),
      CategoryDish(id: 'c-ks-b4', name: 'Harisa Breakfast', description: 'Slow-cooked meat porridge, winter warmth.', timeMinutes: 90),
      CategoryDish(id: 'c-ks-b5', name: 'Bakarkhani', description: 'Sweet flaky bread with saffron.', timeMinutes: 40),
    ],
    'healthy': [
      CategoryDish(id: 'c-ks-h1', name: 'Lotus Stem Salad', description: 'Nadru slices with lemon and herbs.', timeMinutes: 20),
      CategoryDish(id: 'c-ks-h2', name: 'Turnip Sabzi', description: 'Gogji cooked light with fennel.', timeMinutes: 30),
      CategoryDish(id: 'c-ks-h3', name: 'Green Bean Khorma', description: 'Light beans in yogurt gravy.', timeMinutes: 30),
      CategoryDish(id: 'c-ks-h4', name: 'Methi Chaman', description: 'Fenugreek with soft cheese, gentle spice.', timeMinutes: 35),
      CategoryDish(id: 'c-ks-h5', name: 'Kahwa Detox', description: 'Green tea with saffron and cinnamon.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-ks-d1', name: 'Rogan Josh', description: 'Signature red lamb curry with fennel.', timeMinutes: 90),
      CategoryDish(id: 'c-ks-d2', name: 'Gushtaba', description: 'Delicate mutton meatballs in yogurt gravy.', timeMinutes: 90),
      CategoryDish(id: 'c-ks-d3', name: 'Yakhni', description: 'Yogurt-based mutton stew with spices.', timeMinutes: 85),
      CategoryDish(id: 'c-ks-d4', name: 'Dum Aloo Kashmiri', description: 'Baby potatoes in asafoetida-rich gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-ks-d5', name: 'Nadru Yakhni', description: 'Lotus stem in a mild yogurt curry.', timeMinutes: 45),
    ],
    'veg': [
      CategoryDish(id: 'c-ks-v1', name: 'Dum Aloo', description: 'Potatoes in a fennel-yogurt gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-ks-v2', name: 'Nadru Monji', description: 'Lotus stem stir-fry with spices.', timeMinutes: 30),
      CategoryDish(id: 'c-ks-v3', name: 'Methi Chaman', description: 'Fenugreek and paneer in a light gravy.', timeMinutes: 35),
      CategoryDish(id: 'c-ks-v4', name: 'Hak', description: 'Collard greens simmered with green chillies.', timeMinutes: 30),
      CategoryDish(id: 'c-ks-v5', name: 'Chok Wangun', description: 'Stir-fried brinjal with mustard oil.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ks-n1', name: 'Rogan Josh', description: 'Aromatic lamb curry with fennel and red chillies.', timeMinutes: 90),
      CategoryDish(id: 'c-ks-n2', name: 'Yakhni', description: 'Gentle yogurt mutton stew.', timeMinutes: 85),
      CategoryDish(id: 'c-ks-n3', name: 'Tabak Maaz', description: 'Fried lamb ribs, crisp and spiced.', timeMinutes: 60),
      CategoryDish(id: 'c-ks-n4', name: 'Aab Gosh', description: 'Mutton in milk, perfumed with cardamom.', timeMinutes: 90),
      CategoryDish(id: 'c-ks-n5', name: 'Chicken Thukpa', description: 'Warming chicken noodle soup.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-ks-s1', name: 'Phirni Kashmiri', description: 'Ground rice pudding with saffron and nuts.', timeMinutes: 40),
      CategoryDish(id: 'c-ks-s2', name: 'Kulfi Falooda', description: 'Traditional dense kulfi with noodles.', timeMinutes: 40),
      CategoryDish(id: 'c-ks-s3', name: 'Shufta', description: 'Dry fruit mix with saffron and honey.', timeMinutes: 20),
      CategoryDish(id: 'c-ks-s4', name: 'Lauki Halwa', description: 'Bottle gourd halwa with ghee.', timeMinutes: 40),
      CategoryDish(id: 'c-ks-s5', name: 'Kong Phirni', description: 'Saffron rice pudding served warm.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-ks-k1', name: 'Sweet Noon Chai', description: 'Pink tea made mild and sweet.', timeMinutes: 20),
      CategoryDish(id: 'c-ks-k2', name: 'Girda with Jam', description: 'Soft bun with fruit jam.', timeMinutes: 25),
      CategoryDish(id: 'c-ks-k3', name: 'Kahwa Milk', description: 'Warm milk with a pinch of saffron.', timeMinutes: 15),
      CategoryDish(id: 'c-ks-k4', name: 'Bakarkhani Bite', description: 'Small sweet bread squares.', timeMinutes: 30),
      CategoryDish(id: 'c-ks-k5', name: 'Mild Dum Aloo', description: 'Baby potatoes in a mild gravy.', timeMinutes: 40),
    ],
  },
};
