import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart1 = {
  'bihari': {
    'breakfast': [
      CategoryDish(id: 'c-bi-b1', name: 'Sattu Paratha', description: 'Whole-wheat flatbread stuffed with spiced sattu and onion.', timeMinutes: 25),
      CategoryDish(id: 'c-bi-b2', name: 'Chura Dahi', description: 'Flattened rice with sweet yogurt and jaggery.', timeMinutes: 10),
      CategoryDish(id: 'c-bi-b3', name: 'Litti Breakfast', description: 'Baked sattu balls brushed with ghee, served with chokha.', timeMinutes: 40),
      CategoryDish(id: 'c-bi-b4', name: 'Chokha with Puri', description: 'Mashed roasted vegetables with puffed wheat bread.', timeMinutes: 30),
      CategoryDish(id: 'c-bi-b5', name: 'Malpua', description: 'Semolina pancakes in sugar syrup with rabri.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-bi-h1', name: 'Sattu Drink', description: 'Whipped roasted gram flour with lemon, mint and black salt.', timeMinutes: 10),
      CategoryDish(id: 'c-bi-h2', name: 'Moong Sprout Chaat', description: 'Sprouted moong tossed with onion, lemon and chaat masala.', timeMinutes: 15),
      CategoryDish(id: 'c-bi-h3', name: 'Bharwa Bhindi', description: 'Stuffed okra roasted with little oil and spices.', timeMinutes: 30),
      CategoryDish(id: 'c-bi-h4', name: 'Lauki Sabzi', description: 'Bottle gourd simmered with ginger and cumin.', timeMinutes: 25),
      CategoryDish(id: 'c-bi-h5', name: 'Baingan Bharta', description: 'Roasted eggplant mash with tomato and coriander, light on ghee.', timeMinutes: 35),
    ],
    'dinner': [
      CategoryDish(id: 'c-bi-d1', name: 'Litti Chokha', description: 'Classic Bihari sattu balls with mashed roasted vegetables.', timeMinutes: 60),
      CategoryDish(id: 'c-bi-d2', name: 'Bihari Mutton Curry', description: 'Slow-cooked mutton in rustic onion-garlic masala.', timeMinutes: 80),
      CategoryDish(id: 'c-bi-d3', name: 'Arhar Dal', description: 'Toor dal with a punchy garlic-red chilli tempering.', timeMinutes: 35),
      CategoryDish(id: 'c-bi-d4', name: 'Palak Paneer', description: 'Paneer cubes in creamy spinach gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-bi-d5', name: 'Dal Bati Bihari', description: 'Wheat balls with spiced dal and ghee.', timeMinutes: 55),
    ],
    'veg': [
      CategoryDish(id: 'c-bi-v1', name: 'Aloo Bharta', description: 'Mashed potato with green chilli, onion and mustard oil.', timeMinutes: 20),
      CategoryDish(id: 'c-bi-v2', name: 'Bhindi Fry', description: 'Crisp okra fried with turmeric and amchur.', timeMinutes: 25),
      CategoryDish(id: 'c-bi-v3', name: 'Kadhi Badi', description: 'Yogurt curry with fried gram-flour dumplings.', timeMinutes: 45),
      CategoryDish(id: 'c-bi-v4', name: 'Tamatar Chokha', description: 'Roasted tomato and eggplant mash with mustard oil.', timeMinutes: 25),
      CategoryDish(id: 'c-bi-v5', name: 'Ragda Aloo', description: 'White peas curry over spiced potato.', timeMinutes: 45),
    ],
    'nonveg': [
      CategoryDish(id: 'c-bi-n1', name: 'Bihari Chicken Curry', description: 'Chicken simmered with potato and earthy spices.', timeMinutes: 55),
      CategoryDish(id: 'c-bi-n2', name: 'Fish Bhuna', description: 'Mustard-marinated fish cooked in a dry masala.', timeMinutes: 35),
      CategoryDish(id: 'c-bi-n3', name: 'Mutton Korma', description: 'Mutton in a rich yogurt-based gravy.', timeMinutes: 80),
      CategoryDish(id: 'c-bi-n4', name: 'Bihari Egg Curry', description: 'Boiled eggs in a tangy onion-tomato gravy.', timeMinutes: 30),
      CategoryDish(id: 'c-bi-n5', name: 'Chicken Seekh Kebab', description: 'Char-grilled minced chicken with warm spices.', timeMinutes: 40),
    ],
    'sweet': [
      CategoryDish(id: 'c-bi-s1', name: 'Thekua', description: 'Crisp jaggery and wheat cookies, a Bihari festival treat.', timeMinutes: 45),
      CategoryDish(id: 'c-bi-s2', name: 'Khurma', description: 'Fried vermicelli cooked in milk with nuts.', timeMinutes: 40),
      CategoryDish(id: 'c-bi-s3', name: 'Anarsa', description: 'Rice-flour and jaggery sweet fritters.', timeMinutes: 50),
      CategoryDish(id: 'c-bi-s4', name: 'Makhana Kheer', description: 'Fox nuts simmered in milk with cardamom.', timeMinutes: 30),
      CategoryDish(id: 'c-bi-s5', name: 'Tilwa', description: 'Sesame and jaggery squares, crunchy and sweet.', timeMinutes: 25),
    ],
    'kids': [
      CategoryDish(id: 'c-bi-k1', name: 'Sattu Laddoo', description: 'Roasted gram-flour energy balls with jaggery.', timeMinutes: 20),
      CategoryDish(id: 'c-bi-k2', name: 'Bhutta', description: 'Grilled corn on the cob with lemon and salt.', timeMinutes: 15),
      CategoryDish(id: 'c-bi-k3', name: 'Aloo Puri', description: 'Puffed bread with a mild potato curry.', timeMinutes: 35),
      CategoryDish(id: 'c-bi-k4', name: 'Chura with Banana', description: 'Flattened rice with banana and jaggery.', timeMinutes: 10),
      CategoryDish(id: 'c-bi-k5', name: 'Mini Malpua', description: 'Small sweet semolina pancakes kids love.', timeMinutes: 25),
    ],
  },
  'jharkhandi': {
    'breakfast': [
      CategoryDish(id: 'c-jh-b1', name: 'Dhuska', description: 'Crisp rice and chana dal pancakes.', timeMinutes: 35),
      CategoryDish(id: 'c-jh-b2', name: 'Litti Chokha', description: 'Sattu-filled wheat balls with mashed vegetables.', timeMinutes: 40),
      CategoryDish(id: 'c-jh-b3', name: 'Rugra Omelette', description: 'Wild mushroom omelette, a tribal breakfast.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-b4', name: 'Chilka Roti', description: 'Thin rice flatbread from the tribal belt.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-b5', name: 'Kadhi with Rice', description: 'Tangy yogurt curry over steamed rice.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-jh-h1', name: 'Arsa Dal Soup', description: 'Light lentil soup with turmeric and garlic.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-h2', name: 'Mixed Grain Khichdi', description: 'Rice with sprouted moong and vegetables.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-h3', name: 'Kandha Sabzi', description: 'Yam cooked with minimal oil and spices.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-h4', name: 'Mushroom Palak', description: 'Rugra mushrooms with spinach and garlic.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-h5', name: 'Black Gram Chaat', description: 'Sprouted black gram with lemon and herbs.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-jh-d1', name: 'Chicken Jagdal', description: 'Tribal chicken curry with roasted spices.', timeMinutes: 60),
      CategoryDish(id: 'c-jh-d2', name: 'Peeled Mung Dal', description: 'Mung dal tempered with ghee and cumin.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-d3', name: 'Pittha', description: 'Steamed rice dumplings with a spiced filling.', timeMinutes: 50),
      CategoryDish(id: 'c-jh-d4', name: 'Rugra Sabzi', description: 'Wild mushrooms cooked with onion and garlic.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-d5', name: 'Handia Rice', description: 'Steamed rice served with fermented rice beer side.', timeMinutes: 25),
    ],
    'veg': [
      CategoryDish(id: 'c-jh-v1', name: 'Kadhi Badis', description: 'Yogurt curry with fried gram dumplings.', timeMinutes: 40),
      CategoryDish(id: 'c-jh-v2', name: 'Aloo Chokha', description: 'Smoky mashed potato with green chilli.', timeMinutes: 20),
      CategoryDish(id: 'c-jh-v3', name: 'Kaddu Sabzi', description: 'Pumpkin cooked with mustard seeds.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-v4', name: 'Chana Dal Fry', description: 'Bengal gram dal with garlic tempering.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-v5', name: 'Mixed Veg Stew', description: 'Forest vegetables simmered with ginger.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-jh-n1', name: 'Mutton Kaliya', description: 'Rich mutton gravy cooked over a slow fire.', timeMinutes: 85),
      CategoryDish(id: 'c-jh-n2', name: 'Fish Pakora', description: 'Crisp batter-fried river fish.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-n3', name: 'Chicken Pitha', description: 'Steamed dumplings stuffed with spiced chicken.', timeMinutes: 55),
      CategoryDish(id: 'c-jh-n4', name: 'Prawn Kalia', description: 'River prawns in a warming masala gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-jh-n5', name: 'Egg Tari', description: 'Hard-boiled eggs in a rustic onion gravy.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-jh-s1', name: 'Thekua', description: 'Jaggery wheat cookies from the tribal kitchen.', timeMinutes: 45),
      CategoryDish(id: 'c-jh-s2', name: 'Malpua', description: 'Griddle-fried pancakes soaked in syrup.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-s3', name: 'Kheer Sandesh', description: 'Rice pudding set with jaggery.', timeMinutes: 35),
      CategoryDish(id: 'c-jh-s4', name: 'Chura Ghee', description: 'Flattened rice with ghee and jaggery.', timeMinutes: 10),
      CategoryDish(id: 'c-jh-s5', name: 'Arsa', description: 'Rice and jaggery fritters, crisp outside.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-jh-k1', name: 'Mini Dhuska', description: 'Small rice pancakes with a sweet chutney.', timeMinutes: 30),
      CategoryDish(id: 'c-jh-k2', name: 'Corn Bhutta', description: 'Roasted corn rubbed with lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-jh-k3', name: 'Sweet Rice', description: 'Jaggery-sweetened rice with cardamom.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-k4', name: 'Aloo Balls', description: 'Golden potato balls with a soft centre.', timeMinutes: 25),
      CategoryDish(id: 'c-jh-k5', name: 'Banana Halwa', description: 'Sweet banana mash with ghee and nuts.', timeMinutes: 20),
    ],
  },
  'assamese': {
    'breakfast': [
      CategoryDish(id: 'c-as-b1', name: 'Pitha with Curd', description: 'Rice pancakes with yogurt and jaggery.', timeMinutes: 30),
      CategoryDish(id: 'c-as-b2', name: 'Jolpan', description: 'Flattened rice with yogurt, jaggery and banana.', timeMinutes: 10),
      CategoryDish(id: 'c-as-b3', name: 'Murir Kheer', description: 'Puffed rice cooked in milk and jaggery.', timeMinutes: 20),
      CategoryDish(id: 'c-as-b4', name: 'Til Pitha', description: 'Sesame-filled rice cakes, pan-fried.', timeMinutes: 35),
      CategoryDish(id: 'c-as-b5', name: 'Kumol Saul', description: 'Soaked soft rice with yogurt and banana.', timeMinutes: 10),
    ],
    'healthy': [
      CategoryDish(id: 'c-as-h1', name: 'Green Lentil Stew', description: 'Moong dal simmered with ginger and garlic.', timeMinutes: 30),
      CategoryDish(id: 'c-as-h2', name: 'Bottle Gourd Sabzi', description: 'Lauki cooked with mustard seeds and curry leaves.', timeMinutes: 25),
      CategoryDish(id: 'c-as-h3', name: 'Spinach Banana Leaf', description: 'Steamed leafy greens with mustard paste.', timeMinutes: 30),
      CategoryDish(id: 'c-as-h4', name: 'Black Rice Porridge', description: 'Kola saul cooked with milk and jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-as-h5', name: 'Pumpkin Flower Fry', description: 'Delicate pumpkin flowers pan-fried lightly.', timeMinutes: 20),
    ],
    'dinner': [
      CategoryDish(id: 'c-as-d1', name: 'Masor Tenga', description: 'Tangy fish curry with tomatoes and lemon.', timeMinutes: 45),
      CategoryDish(id: 'c-as-d2', name: 'Khar', description: 'Traditional alkaline curry with papaya and pulses.', timeMinutes: 35),
      CategoryDish(id: 'c-as-d3', name: 'Bilahi Maas', description: 'Fish simmered in a tomato-ginger gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-as-d4', name: 'Xukuti', description: 'Smoked and dried fish curry.', timeMinutes: 45),
      CategoryDish(id: 'c-as-d5', name: 'Aloo Pitika', description: 'Mashed potato with mustard oil and chillies.', timeMinutes: 15),
    ],
    'veg': [
      CategoryDish(id: 'c-as-v1', name: 'Aloo Pitika', description: 'Smoky mashed potato with mustard oil.', timeMinutes: 15),
      CategoryDish(id: 'c-as-v2', name: 'Bilahi Pitika', description: 'Roasted tomato mash with coriander.', timeMinutes: 15),
      CategoryDish(id: 'c-as-v3', name: 'Khira Sabzi', description: 'Cucumber and potato stir-fry.', timeMinutes: 20),
      CategoryDish(id: 'c-as-v4', name: 'Dal Dail', description: 'Split pea dal tempered with panch phoron.', timeMinutes: 30),
      CategoryDish(id: 'c-as-v5', name: 'Brinjal Khar', description: 'Eggplant in a smoky alkaline gravy.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-as-n1', name: 'Masor Tenga', description: 'Sour and tangy fish curry with fresh herbs.', timeMinutes: 45),
      CategoryDish(id: 'c-as-n2', name: 'Chicken Xukuti', description: 'Smoked chicken curry with bamboo shoot.', timeMinutes: 55),
      CategoryDish(id: 'c-as-n3', name: 'Duck Roast', description: 'Slow-roasted duck in onion and ginger masala.', timeMinutes: 90),
      CategoryDish(id: 'c-as-n4', name: 'Prawn Tenga', description: 'River prawns in a lemony tangy gravy.', timeMinutes: 35),
      CategoryDish(id: 'c-as-n5', name: 'Mutton Khorisa', description: 'Mutton cooked with fermented bamboo shoot.', timeMinutes: 80),
    ],
    'sweet': [
      CategoryDish(id: 'c-as-s1', name: 'Payox', description: 'Assamese rice pudding with jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-as-s2', name: 'Til Pitha', description: 'Sesame and jaggery stuffed rice cakes.', timeMinutes: 35),
      CategoryDish(id: 'c-as-s3', name: 'Narikol Laru', description: 'Coconut and jaggery laddoos.', timeMinutes: 20),
      CategoryDish(id: 'c-as-s4', name: 'Kumol Saul Kheer', description: 'Soft rice cooked in sweetened milk.', timeMinutes: 30),
      CategoryDish(id: 'c-as-s5', name: 'Ghila Pitha', description: 'Fried jaggery-sweetened rice cakes.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-as-k1', name: 'Banana Jolpan', description: 'Flattened rice with banana and jaggery.', timeMinutes: 10),
      CategoryDish(id: 'c-as-k2', name: 'Mini Pitha', description: 'Small rice pancakes with jaggery filling.', timeMinutes: 30),
      CategoryDish(id: 'c-as-k3', name: 'Sweet Rice Balls', description: 'Jaggery rice balls rolled in coconut.', timeMinutes: 25),
      CategoryDish(id: 'c-as-k4', name: 'Corn Poha', description: 'Puffed corn with peanuts and lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-as-k5', name: 'Milk Muri', description: 'Puffed rice in sweet milk.', timeMinutes: 10),
    ],
  },
  'manipuri': {
    'breakfast': [
      CategoryDish(id: 'c-mn-b1', name: 'Chak-hao Kheer', description: 'Black rice pudding with jaggery and coconut.', timeMinutes: 40),
      CategoryDish(id: 'c-mn-b2', name: 'Rice with Kanghou', description: 'Steamed rice with a boiled vegetable mash.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-b3', name: 'Paknam Rice', description: 'Steamed rice parcels with herbs.', timeMinutes: 35),
      CategoryDish(id: 'c-mn-b4', name: 'Hingabi', description: 'Mild rice porridge with fermented beans.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-b5', name: 'Singju', description: 'Crunchy salad with lemon and roasted sesame.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-mn-h1', name: 'Utan', description: 'Boiled vegetables mashed with herbs.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-h2', name: 'Chamthong', description: 'Light mixed vegetable stew with ginger.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-h3', name: 'Black Rice Salad', description: 'Chak-hao tossed with greens and lemon.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-h4', name: 'Green Papaya Sabzi', description: 'Raw papaya cooked with minimal oil.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-h5', name: 'Soybean Stew', description: 'Hawaijar-inspired soybean simmered with spices.', timeMinutes: 35),
    ],
    'dinner': [
      CategoryDish(id: 'c-mn-d1', name: 'Eromba', description: 'Boiled veg and fish mash with fermented beans.', timeMinutes: 40),
      CategoryDish(id: 'c-mn-d2', name: 'Ngari Fish Curry', description: 'Fish curry with fermented fish paste.', timeMinutes: 45),
      CategoryDish(id: 'c-mn-d3', name: 'Chicken Morok', description: 'Spicy chicken curry with red chillies.', timeMinutes: 55),
      CategoryDish(id: 'c-mn-d4', name: 'Rice with Thongba', description: 'Steamed rice with a simple dal.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-d5', name: 'Prawn Eromba', description: 'Mashed prawn with herbs and lemon.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-mn-v1', name: 'Kanghou', description: 'Boiled mixed vegetables with toasted sesame.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-v2', name: 'Chamthong', description: 'Stew of seasonal vegetables and ginger.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-v3', name: 'Singju Salad', description: 'Cabbage salad with roasted gram and lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-mn-v4', name: 'Utan Green', description: 'Leafy greens mashed with chilli and salt.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-v5', name: 'Bean Stir-fry', description: 'Long beans with mustard seeds and onion.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-mn-n1', name: 'Ngari Fish', description: 'Fermented fish simmered with herbs.', timeMinutes: 35),
      CategoryDish(id: 'c-mn-n2', name: 'Chicken Eromba', description: 'Chicken and veg mash with fermented bean.', timeMinutes: 50),
      CategoryDish(id: 'c-mn-n3', name: 'Prawn Morok', description: 'Fiery prawn curry with dry chillies.', timeMinutes: 35),
      CategoryDish(id: 'c-mn-n4', name: 'Duck Thongba', description: 'Slow duck curry with lentils and spices.', timeMinutes: 90),
      CategoryDish(id: 'c-mn-n5', name: 'Smoked Fish Sabzi', description: 'Smoked river fish with green chilli.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-mn-s1', name: 'Chak-hao Payesh', description: 'Black rice pudding with jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-mn-s2', name: 'Coconut Ladoo', description: 'Sweet coconut and jaggery balls.', timeMinutes: 20),
      CategoryDish(id: 'c-mn-s3', name: 'Rice Flour Halwa', description: 'Silky rice-flour halwa with ghee.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-s4', name: 'Jaggery Rice', description: 'Sticky sweet rice with cardamom.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-s5', name: 'Fried Sesame Puffs', description: 'Sesame-jaggery squares, crisp and sweet.', timeMinutes: 25),
    ],
    'kids': [
      CategoryDish(id: 'c-mn-k1', name: 'Sweet Black Rice', description: 'Mildly sweet chak-hao with milk.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-k2', name: 'Banana Rice Balls', description: 'Soft rice balls with banana and jaggery.', timeMinutes: 25),
      CategoryDish(id: 'c-mn-k3', name: 'Mild Singju', description: 'Crunchy cabbage salad, low spice.', timeMinutes: 15),
      CategoryDish(id: 'c-mn-k4', name: 'Coconut Rice', description: 'Sweet coconut rice with raisins.', timeMinutes: 30),
      CategoryDish(id: 'c-mn-k5', name: 'Puffed Rice Chaat', description: 'Puffed rice with lemon and peanut.', timeMinutes: 10),
    ],
  },
  'naga': {
    'breakfast': [
      CategoryDish(id: 'c-na-b1', name: 'Rice with Axone', description: 'Steamed rice with fermented soybean chutney.', timeMinutes: 25),
      CategoryDish(id: 'c-na-b2', name: 'Boiled Veg Salad', description: 'Crunchy boiled vegetables with chilli and onion.', timeMinutes: 20),
      CategoryDish(id: 'c-na-b3', name: 'Smoked Pork Omelette', description: 'Omelette with smoky pork bits and chilli.', timeMinutes: 25),
      CategoryDish(id: 'c-na-b4', name: 'Rice Porridge', description: 'Simple rice porridge with ginger and salt.', timeMinutes: 25),
      CategoryDish(id: 'c-na-b5', name: 'Corn on Fire', description: 'Charred corn with local chilli salt.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-na-h1', name: 'Fermented Soybean Stew', description: 'Protein-rich axone broth with greens.', timeMinutes: 35),
      CategoryDish(id: 'c-na-h2', name: 'Boiled Greens', description: 'Seasonal greens with mustard and chilli.', timeMinutes: 20),
      CategoryDish(id: 'c-na-h3', name: 'Bamboo Shoot Sabzi', description: 'Tender bamboo shoot cooked lightly.', timeMinutes: 25),
      CategoryDish(id: 'c-na-h4', name: 'Chilli Chicken Broth', description: 'Light chicken soup with bird chillies.', timeMinutes: 40),
      CategoryDish(id: 'c-na-h5', name: 'Local Bean Salad', description: 'Boiled beans with onion and lime.', timeMinutes: 20),
    ],
    'dinner': [
      CategoryDish(id: 'c-na-d1', name: 'Smoked Pork Curry', description: 'Smoked pork simmered with bamboo shoot.', timeMinutes: 70),
      CategoryDish(id: 'c-na-d2', name: 'Naga Chicken Curry', description: 'Fiery chicken curry with ghost chillies.', timeMinutes: 55),
      CategoryDish(id: 'c-na-d3', name: 'Pork with Axone', description: 'Pork cooked with fermented soybean paste.', timeMinutes: 70),
      CategoryDish(id: 'c-na-d4', name: 'Fish Stew', description: 'River fish stew with herbs and chillies.', timeMinutes: 40),
      CategoryDish(id: 'c-na-d5', name: 'Steamed Rice Meal', description: 'Steamed rice with a spiced side.', timeMinutes: 30),
    ],
    'veg': [
      CategoryDish(id: 'c-na-v1', name: 'Boiled Pumpkin', description: 'Steamed pumpkin with chilli salt.', timeMinutes: 20),
      CategoryDish(id: 'c-na-v2', name: 'Soybean Chutney', description: 'Axone paste with green chilli and onion.', timeMinutes: 20),
      CategoryDish(id: 'c-na-v3', name: 'Bamboo Shoot Fry', description: 'Sliced bamboo shoot stir-fried crisp.', timeMinutes: 20),
      CategoryDish(id: 'c-na-v4', name: 'Green Bean Sabzi', description: 'Beans cooked with mustard and chilli.', timeMinutes: 20),
      CategoryDish(id: 'c-na-v5', name: 'Kohlrabi Stew', description: 'Turnip and kohlrabi simmered with ginger.', timeMinutes: 25),
    ],
    'nonveg': [
      CategoryDish(id: 'c-na-n1', name: 'Smoked Pork Curry', description: 'Slow-cooked smoky pork with bamboo shoot.', timeMinutes: 70),
      CategoryDish(id: 'c-na-n2', name: 'Beef Dry Roast', description: 'Beef roasted with ginger and chillies.', timeMinutes: 60),
      CategoryDish(id: 'c-na-n3', name: 'Chicken Morok', description: 'Chicken with bird\'s eye chillies and garlic.', timeMinutes: 55),
      CategoryDish(id: 'c-na-n4', name: 'Pork Liver Fry', description: 'Crisp pork liver with chilli and onion.', timeMinutes: 30),
      CategoryDish(id: 'c-na-n5', name: 'Prawn with Herbs', description: 'River prawns with herbs and lime.', timeMinutes: 35),
    ],
    'sweet': [
      CategoryDish(id: 'c-na-s1', name: 'Rice Pudding', description: 'Rice cooked in milk with jaggery.', timeMinutes: 35),
      CategoryDish(id: 'c-na-s2', name: 'Steamed Banana', description: 'Banana steamed and drizzled with honey.', timeMinutes: 15),
      CategoryDish(id: 'c-na-s3', name: 'Corn Custard', description: 'Sweet corn pudding with cardamom.', timeMinutes: 30),
      CategoryDish(id: 'c-na-s4', name: 'Jaggery Rice Balls', description: 'Sweet rice dumplings rolled in sesame.', timeMinutes: 30),
      CategoryDish(id: 'c-na-s5', name: 'Honey Sesame Squares', description: 'Toasted sesame bound with honey.', timeMinutes: 20),
    ],
    'kids': [
      CategoryDish(id: 'c-na-k1', name: 'Mild Chicken Rice', description: 'Soft chicken rice, easy on the spice.', timeMinutes: 35),
      CategoryDish(id: 'c-na-k2', name: 'Sweet Corn Bowl', description: 'Warm corn with butter and a pinch of salt.', timeMinutes: 15),
      CategoryDish(id: 'c-na-k3', name: 'Banana Rice', description: 'Rice with mashed banana and jaggery.', timeMinutes: 20),
      CategoryDish(id: 'c-na-k4', name: 'Boiled Potato Bites', description: 'Steamed potato with mild seasoning.', timeMinutes: 20),
      CategoryDish(id: 'c-na-k5', name: 'Honey Bread', description: 'Toasted bread with honey drizzle.', timeMinutes: 10),
    ],
  },
};
