import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart7 = {
  'karnataka': {
    'breakfast': [
      CategoryDish(id: 'c-ka-b1', name: 'Idli Vada', description: 'Steamed idli with crisp vada.', timeMinutes: 40),
      CategoryDish(id: 'c-ka-b2', name: 'Mysore Masala Dosa', description: 'Dosa with red chutney and potatoes.', timeMinutes: 35),
      CategoryDish(id: 'c-ka-b3', name: 'Akki Rotti', description: 'Crisp rice-flour flatbread.', timeMinutes: 30),
      CategoryDish(id: 'c-ka-b4', name: 'Kesari Bath', description: 'Sweet saffron semolina.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-b5', name: 'Khara Bath', description: 'Spicy vegetable semolina.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-ka-h1', name: 'Ragi Mudde with Soppu', description: 'Finger-millet balls with greens.', timeMinutes: 40),
      CategoryDish(id: 'c-ka-h2', name: 'Palya', description: 'Lightly spiced vegetable stir-fry.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-h3', name: 'Sambar Light', description: 'Lentil soup with vegetables.', timeMinutes: 35),
      CategoryDish(id: 'c-ka-h4', name: 'Cucumber Salad', description: 'Mooli and cucumber salad.', timeMinutes: 10),
      CategoryDish(id: 'c-ka-h5', name: 'Millet Khichdi', description: 'Millet and lentil one-pot.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-ka-d1', name: 'Bisi Bele Bath', description: 'Spicy lentil-rice hotchpotch.', timeMinutes: 45),
      CategoryDish(id: 'c-ka-d2', name: 'Ghee Roast Dosa', description: 'Crisp dosa with potato saagu.', timeMinutes: 35),
      CategoryDish(id: 'c-ka-d3', name: 'Meals Curry Set', description: 'Rice with sambar and palya.', timeMinutes: 45),
      CategoryDish(id: 'c-ka-d4', name: 'Chitranna', description: 'Tamarind lemon rice.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-d5', name: 'Ragi Mudde Dinner', description: 'Millet balls with sambar.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-ka-v1', name: 'Bisi Bele Bath', description: 'Classic Bangalore hotchpotch.', timeMinutes: 45),
      CategoryDish(id: 'c-ka-v2', name: 'Chitranna', description: 'Tamarind rice with peanuts.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-v3', name: 'Palya', description: 'Dry vegetable curry.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-v4', name: 'Kosambari', description: 'Moong salad with coconut.', timeMinutes: 15),
      CategoryDish(id: 'c-ka-v5', name: 'Majjige Huli', description: 'Curd-lentil curry.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ka-n1', name: 'Mangalore Chicken', description: 'Kundapur-style fiery chicken.', timeMinutes: 50),
      CategoryDish(id: 'c-ka-n2', name: 'Anjal Fry', description: 'Crisp kingfish fry.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-n3', name: 'Mutton Curry Karnataka', description: 'Robust mutton curry.', timeMinutes: 80),
      CategoryDish(id: 'c-ka-n4', name: 'Kori Gassi', description: 'Chicken in coconut gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-ka-n5', name: 'Prawn Ghee Roast', description: 'Prawns in a fiery roasted masala.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-ka-s1', name: 'Mysore Pak', description: 'Rich ghee-laden fudge.', timeMinutes: 30),
      CategoryDish(id: 'c-ka-s2', name: 'Holige', description: 'Sweet stuffed flatbread.', timeMinutes: 50),
      CategoryDish(id: 'c-ka-s3', name: 'Payasa', description: 'Coconut-milk pudding.', timeMinutes: 35),
      CategoryDish(id: 'c-ka-s4', name: 'Kesari Bath', description: 'Saffron semolina sweet.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-s5', name: 'Rava Laddu', description: 'Semolina-ghee sweet balls.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-ka-k1', name: 'Mini Idli', description: 'Small steamed rice cakes.', timeMinutes: 35),
      CategoryDish(id: 'c-ka-k2', name: 'Sweet Kesari Cup', description: 'Small saffron sweet.', timeMinutes: 25),
      CategoryDish(id: 'c-ka-k3', name: 'Dosa Bite', description: 'Small crisp dosa pieces.', timeMinutes: 30),
      CategoryDish(id: 'c-ka-k4', name: 'Mysore Pak Bite', description: 'A piece of soft sweet fudge.', timeMinutes: 30),
      CategoryDish(id: 'c-ka-k5', name: 'Chitranna Bowl', description: 'Mild lemon-tamarind rice.', timeMinutes: 25),
    ],
  },
  'kerala': {
    'breakfast': [
      CategoryDish(id: 'c-ke-b1', name: 'Appam and Stew', description: 'Lacy pancakes with coconut stew.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-b2', name: 'Puttu Kadala', description: 'Steamed rice cakes with chickpea curry.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-b3', name: 'Idiyappam', description: 'String hoppers with egg curry.', timeMinutes: 35),
      CategoryDish(id: 'c-ke-b4', name: 'Dosa Kerala', description: 'Thin crispy dosa with chutney.', timeMinutes: 30),
      CategoryDish(id: 'c-ke-b5', name: 'Vellayappam', description: 'Soft fermented rice pancake.', timeMinutes: 40),
    ],
    'healthy': [
      CategoryDish(id: 'c-ke-h1', name: 'Thoran', description: 'Shredded greens with coconut.', timeMinutes: 25),
      CategoryDish(id: 'c-ke-h2', name: 'Moru Kachiyathu', description: 'Warm spiced buttermilk curry.', timeMinutes: 25),
      CategoryDish(id: 'c-ke-h3', name: 'Rasam Kerala', description: 'Tangy pepper broth.', timeMinutes: 25),
      CategoryDish(id: 'c-ke-h4', name: 'Avial', description: 'Coconut and curd vegetables.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-h5', name: 'Cabbage Thoran', description: 'Light cabbage with coconut.', timeMinutes: 25),
    ],
    'dinner': [
      CategoryDish(id: 'c-ke-d1', name: 'Fish Molly', description: 'Fish in a mild coconut curry.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-d2', name: 'Kerala Chicken Curry', description: 'Chicken in a coconut-ginger gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-ke-d3', name: 'Meen Curry', description: 'Fish in a tangy tamarind curry.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-d4', name: 'Nadan Beef', description: 'Slow-cooked Kerala beef fry.', timeMinutes: 90),
      CategoryDish(id: 'c-ke-d5', name: 'Kerala Veg Stew', description: 'Vegetables in coconut milk.', timeMinutes: 35),
    ],
    'veg': [
      CategoryDish(id: 'c-ke-v1', name: 'Avial', description: 'Mixed vegetables in curd-coconut.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-v2', name: 'Kerala Sadya Style', description: 'Banana leaf meals basics.', timeMinutes: 45),
      CategoryDish(id: 'c-ke-v3', name: 'Thoran', description: 'Greens with coconut.', timeMinutes: 25),
      CategoryDish(id: 'c-ke-v4', name: 'Moru Curry', description: 'Buttermilk curry with spices.', timeMinutes: 25),
      CategoryDish(id: 'c-ke-v5', name: 'Kootu Curry', description: 'Banana and lentil curry.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ke-n1', name: 'Meen Pollichathu', description: 'Fish steamed in a banana leaf.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-n2', name: 'Kerala Beef Fry', description: 'Crisp fried beef bites.', timeMinutes: 90),
      CategoryDish(id: 'c-ke-n3', name: 'Chemmeen Curry', description: 'Prawns in coconut curry.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-n4', name: 'Chicken Stew Kerala', description: 'Mild chicken in coconut milk.', timeMinutes: 45),
      CategoryDish(id: 'c-ke-n5', name: 'Meen Varuthathu', description: 'Crisp fried fish.', timeMinutes: 25),
    ],
    'sweet': [
      CategoryDish(id: 'c-ke-s1', name: 'Payasam Kerala', description: 'Rice and jaggery pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-s2', name: 'Unniyappam', description: 'Sweet fried rice balls.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-s3', name: 'Palada Payasam', description: 'Milk pudding with rice flakes.', timeMinutes: 45),
      CategoryDish(id: 'c-ke-s4', name: 'Ada Pradhaman', description: 'Rice-flake payasam with jaggery.', timeMinutes: 45),
      CategoryDish(id: 'c-ke-s5', name: 'Neyyappam', description: 'Ghee-fried sweet cakes.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-ke-k1', name: 'Appam Bite', description: 'Small lacy pancakes.', timeMinutes: 35),
      CategoryDish(id: 'c-ke-k2', name: 'Payasam Cup', description: 'Sweet rice pudding cup.', timeMinutes: 40),
      CategoryDish(id: 'c-ke-k3', name: 'Idiyappam Bowl', description: 'Soft string hoppers.', timeMinutes: 35),
      CategoryDish(id: 'c-ke-k4', name: 'Banana Ada', description: 'Sweet banana-steam parcel.', timeMinutes: 30),
      CategoryDish(id: 'c-ke-k5', name: 'Puttu with Banana', description: 'Rice cake with ripe banana.', timeMinutes: 30),
    ],
  },
  'tamil': {
    'breakfast': [
      CategoryDish(id: 'c-ta-b1', name: 'Sambar Idli', description: 'Soft idli drenched in sambar.', timeMinutes: 35),
      CategoryDish(id: 'c-ta-b2', name: 'Pongal', description: 'Pepper-ginger rice and moong dal.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-b3', name: 'Rava Idli', description: 'Steamed semolina cakes.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-b4', name: 'Ven Pongal', description: 'Comforting savoury pongal.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-b5', name: 'Dosa with Chutney', description: 'Crisp dosa with coconut chutney.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-ta-h1', name: 'Rasam', description: 'Tamarind pepper soup.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-h2', name: 'Keerai Kootu', description: 'Greens with lentils.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-h3', name: 'Mor Kuzhambu', description: 'Buttermilk curry with vegetables.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-h4', name: 'Thogayal', description: 'Thick lentil chutney with rice.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-h5', name: 'Curd Rice', description: 'Cool rice with yogurt.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-ta-d1', name: 'Chettinad Chicken', description: 'Fiery Chettinad spice blend.', timeMinutes: 55),
      CategoryDish(id: 'c-ta-d2', name: 'Lemon Rice', description: 'Tangy tempered rice.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-d3', name: 'Sambar', description: 'Lentil and vegetable stew.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-d4', name: 'Kuzhambu', description: 'Sour tamarind curry with rice.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-d5', name: 'Tomato Rice', description: 'Spicy tomato rice.', timeMinutes: 30),
    ],
    'veg': [
      CategoryDish(id: 'c-ta-v1', name: 'Sambar', description: 'The classic lentil stew.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-v2', name: 'Curd Rice', description: 'Mild yogurt rice.', timeMinutes: 15),
      CategoryDish(id: 'c-ta-v3', name: 'Poriyal', description: 'Dry veg stir-fry.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-v4', name: 'Rasam', description: 'Warming pepper soup.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-v5', name: 'Avial Tamil', description: 'Vegetables with coconut.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ta-n1', name: 'Chettinad Chicken', description: 'Boldly spiced chicken.', timeMinutes: 55),
      CategoryDish(id: 'c-ta-n2', name: 'Fish Pulusu', description: 'Tangy fish curry.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-n3', name: 'Mutton Chukka', description: 'Dry masala mutton.', timeMinutes: 85),
      CategoryDish(id: 'c-ta-n4', name: 'Prawn Chettinad', description: 'Prawns in roasted spices.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-n5', name: 'Meen Kuzhambu', description: 'Sour-spicy fish gravy.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-ta-s1', name: 'Payasam Tamil', description: 'Milk and rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-s2', name: 'Kesari', description: 'Saffron semolina sweet.', timeMinutes: 25),
      CategoryDish(id: 'c-ta-s3', name: 'Halwa Tamil', description: 'Wheat halwa.', timeMinutes: 45),
      CategoryDish(id: 'c-ta-s4', name: 'Adhirasam', description: 'Jaggery-rice fritters.', timeMinutes: 45),
      CategoryDish(id: 'c-ta-s5', name: 'Paruppu Payasam', description: 'Moong dal pudding.', timeMinutes: 35),
    ],
    'kids': [
      CategoryDish(id: 'c-ta-k1', name: 'Mini Idli with Sambar', description: 'Soft bites with mild sambar.', timeMinutes: 35),
      CategoryDish(id: 'c-ta-k2', name: 'Sweet Pongal Cup', description: 'Mild sweet rice.', timeMinutes: 30),
      CategoryDish(id: 'c-ta-k3', name: 'Curd Rice Bowl', description: 'Cooling yogurt rice.', timeMinutes: 15),
      CategoryDish(id: 'c-ta-k4', name: 'Banana Halwa', description: 'Sweet banana dessert.', timeMinutes: 40),
      CategoryDish(id: 'c-ta-k5', name: 'Dosa Roll', description: 'Dosa rolled with chutney.', timeMinutes: 30),
    ],
  },
  'telugu': {
    'breakfast': [
      CategoryDish(id: 'c-te-b1', name: 'Pesarattu', description: 'Green gram dosa with ginger chutney.', timeMinutes: 30),
      CategoryDish(id: 'c-te-b2', name: 'Punugulu', description: 'Crisp fried lentil bites.', timeMinutes: 30),
      CategoryDish(id: 'c-te-b3', name: 'Upma Andhra', description: 'Semolina with peanuts and chillies.', timeMinutes: 20),
      CategoryDish(id: 'c-te-b4', name: 'Idli with Gunpowder', description: 'Idli with spicy podi.', timeMinutes: 35),
      CategoryDish(id: 'c-te-b5', name: 'Gongura Dosa', description: 'Dosa with sorrel chutney.', timeMinutes: 30),
    ],
    'healthy': [
      CategoryDish(id: 'c-te-h1', name: 'Palakura Pappu', description: 'Spinach dal.', timeMinutes: 30),
      CategoryDish(id: 'c-te-h2', name: 'Gongura Pappu', description: 'Tangy sorrel dal.', timeMinutes: 35),
      CategoryDish(id: 'c-te-h3', name: 'Vankaya Pulusu', description: 'Brinjal in tamarind gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-te-h4', name: 'Tomato Pappu', description: 'Tomato dal.', timeMinutes: 30),
      CategoryDish(id: 'c-te-h5', name: 'Mudda Pappu', description: 'Plain moong dal with ghee.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-te-d1', name: 'Andhra Chicken Curry', description: 'Fiery home-style chicken.', timeMinutes: 50),
      CategoryDish(id: 'c-te-d2', name: 'Gutti Vankaya', description: 'Stuffed brinjal curry.', timeMinutes: 45),
      CategoryDish(id: 'c-te-d3', name: 'Royyala Iguru', description: 'Prawn curry with onion masala.', timeMinutes: 40),
      CategoryDish(id: 'c-te-d4', name: 'Bobbatlu Combo', description: 'Sweet flatbread with meal.', timeMinutes: 45),
      CategoryDish(id: 'c-te-d5', name: 'Mamsam Vepudu', description: 'Spicy mutton fry.', timeMinutes: 80),
    ],
    'veg': [
      CategoryDish(id: 'c-te-v1', name: 'Gutti Vankaya', description: 'Stuffed brinjals in spice.', timeMinutes: 45),
      CategoryDish(id: 'c-te-v2', name: 'Gongura Pachadi', description: 'Sorrel chutney with rice.', timeMinutes: 30),
      CategoryDish(id: 'c-te-v3', name: 'Aloo Baingan Curry', description: 'Potato and brinjal curry.', timeMinutes: 30),
      CategoryDish(id: 'c-te-v4', name: 'Dal Palak', description: 'Spinach and lentil curry.', timeMinutes: 30),
      CategoryDish(id: 'c-te-v5', name: 'Beans Poriyal', description: 'Crisp beans stir-fry.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-te-n1', name: 'Andhra Chicken Curry', description: 'Hot, tangy and bold.', timeMinutes: 50),
      CategoryDish(id: 'c-te-n2', name: 'Fish Pulusu', description: 'Sour fish stew.', timeMinutes: 40),
      CategoryDish(id: 'c-te-n3', name: 'Kodi Vepudu', description: 'Dry spicy chicken fry.', timeMinutes: 40),
      CategoryDish(id: 'c-te-n4', name: 'Mamsam Vepudu', description: 'Fiery mutton fry.', timeMinutes: 80),
      CategoryDish(id: 'c-te-n5', name: 'Royyala Vepudu', description: 'Crisp chilli prawns.', timeMinutes: 25),
    ],
    'sweet': [
      CategoryDish(id: 'c-te-s1', name: 'Bobbatlu', description: 'Sweet lentil-stuffed flatbread.', timeMinutes: 50),
      CategoryDish(id: 'c-te-s2', name: 'Payasam Telugu', description: 'Milk and vermicelli pudding.', timeMinutes: 30),
      CategoryDish(id: 'c-te-s3', name: 'Arasalu', description: 'Jaggery rice pancakes.', timeMinutes: 35),
      CategoryDish(id: 'c-te-s4', name: 'Sunna Undalu', description: 'Sweet sesame balls.', timeMinutes: 30),
      CategoryDish(id: 'c-te-s5', name: 'Rava Laddu', description: 'Semolina sweet balls.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-te-k1', name: 'Mini Pesarattu', description: 'Small green-gram dosa.', timeMinutes: 30),
      CategoryDish(id: 'c-te-k2', name: 'Sweet Pongal Cup', description: 'Mild sweet rice.', timeMinutes: 30),
      CategoryDish(id: 'c-te-k3', name: 'Curd Rice Bowl', description: 'Cool yogurt rice.', timeMinutes: 15),
      CategoryDish(id: 'c-te-k4', name: 'Bobbatlu Bite', description: 'Sweet flatbread piece.', timeMinutes: 50),
      CategoryDish(id: 'c-te-k5', name: 'Punugulu', description: 'Small crisp fried bites.', timeMinutes: 30),
    ],
  },
  'nepali': {
    'breakfast': [
      CategoryDish(id: 'c-ne-b1', name: 'Aloo Paratha Nepali', description: 'Paratha with spiced potato.', timeMinutes: 35),
      CategoryDish(id: 'c-ne-b2', name: 'Juju Dhau Toast', description: 'Toast with creamy yogurt.', timeMinutes: 10),
      CategoryDish(id: 'c-ne-b3', name: 'Bara', description: 'Lentil patties with egg.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-b4', name: 'Chura with Yogurt', description: 'Flattened rice with curd.', timeMinutes: 15),
      CategoryDish(id: 'c-ne-b5', name: 'Sel Roti Breakfast', description: 'Crisp ring-shaped rice bread.', timeMinutes: 35),
    ],
    'healthy': [
      CategoryDish(id: 'c-ne-h1', name: 'Dal Bhat Light', description: 'Lentil soup with rice.', timeMinutes: 40),
      CategoryDish(id: 'c-ne-h2', name: 'Gundruk Soup', description: 'Fermented greens broth.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-h3', name: 'Khichdi Nepali', description: 'Rice and lentil porridge.', timeMinutes: 35),
      CategoryDish(id: 'c-ne-h4', name: 'Sag', description: 'Sauteed green vegetables.', timeMinutes: 20),
      CategoryDish(id: 'c-ne-h5', name: 'Vegetable Tarkari', description: 'Light mixed veg curry.', timeMinutes: 30),
    ],
    'dinner': [
      CategoryDish(id: 'c-ne-d1', name: 'Dal Bhat', description: 'The national everyday meal.', timeMinutes: 45),
      CategoryDish(id: 'c-ne-d2', name: 'Momo', description: 'Steamed dumplings with chutney.', timeMinutes: 50),
      CategoryDish(id: 'c-ne-d3', name: 'Chicken Curry Nepali', description: 'Home-style chicken curry.', timeMinutes: 50),
      CategoryDish(id: 'c-ne-d4', name: 'Thakali Set', description: 'Set meal with dal and tarkari.', timeMinutes: 45),
      CategoryDish(id: 'c-ne-d5', name: 'Kwati', description: 'Mixed bean soup.', timeMinutes: 60),
    ],
    'veg': [
      CategoryDish(id: 'c-ne-v1', name: 'Aloo Tarkari', description: 'Potato curry with turmeric.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-v2', name: 'Gundruk Tarkari', description: 'Fermented greens curry.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-v3', name: 'Chana Tarkari', description: 'Chickpea curry.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-v4', name: 'Bandgobi Tarkari', description: 'Cabbage curry.', timeMinutes: 25),
      CategoryDish(id: 'c-ne-v5', name: 'Pumpkin Tarkari', description: 'Sweet pumpkin curry.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ne-n1', name: 'Chicken Momo', description: 'Juicy steamed dumplings.', timeMinutes: 50),
      CategoryDish(id: 'c-ne-n2', name: 'Buff Sukuti', description: 'Dry-spiced dried meat.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-n3', name: 'Chicken Curry Nepali', description: 'Warm spiced curry.', timeMinutes: 50),
      CategoryDish(id: 'c-ne-n4', name: 'Chhwela', description: 'Spiced Newari meat salad.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-n5', name: 'Fish Fry Nepali', description: 'Crisp river fish.', timeMinutes: 25),
    ],
    'sweet': [
      CategoryDish(id: 'c-ne-s1', name: 'Juju Dhau', description: 'The king of yogurts.', timeMinutes: 30),
      CategoryDish(id: 'c-ne-s2', name: 'Sel Roti', description: 'Sweet ring-shaped rice bread.', timeMinutes: 35),
      CategoryDish(id: 'c-ne-s3', name: 'Yomari', description: 'Steamed sweet dumplings.', timeMinutes: 55),
      CategoryDish(id: 'c-ne-s4', name: 'Kheer Nepali', description: 'Rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-ne-s5', name: 'Mithai', description: 'Assorted sweet bites.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-ne-k1', name: 'Mini Momo', description: 'Small steamed dumplings.', timeMinutes: 50),
      CategoryDish(id: 'c-ne-k2', name: 'Chura Bowl', description: 'Flattened rice with yogurt.', timeMinutes: 15),
      CategoryDish(id: 'c-ne-k3', name: 'Sel Roti Bite', description: 'Sweet rice bread rings.', timeMinutes: 35),
      CategoryDish(id: 'c-ne-k4', name: 'Khichdi Bowl', description: 'Mild rice-lentil bowl.', timeMinutes: 35),
      CategoryDish(id: 'c-ne-k5', name: 'Juju Dhau Cup', description: 'Sweet creamy yogurt.', timeMinutes: 20),
    ],
  },
};
