import 'category_catalog.dart';

const Map<String, Map<String, List<CategoryDish>>> cuisineCategoryDishesPart4 = {
  'north_indian': {
    'breakfast': [
      CategoryDish(id: 'c-ni-b1', name: 'Aloo Paratha', description: 'Potato-stuffed paratha with butter and curd.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-b2', name: 'Poha', description: 'Flattened rice with peanuts, onion and lemon.', timeMinutes: 20),
      CategoryDish(id: 'c-ni-b3', name: 'Chole Bhature', description: 'Spiced chickpeas with puffed bread.', timeMinutes: 50),
      CategoryDish(id: 'c-ni-b4', name: 'Upma', description: 'Semolina with vegetables and curry leaves.', timeMinutes: 20),
      CategoryDish(id: 'c-ni-b5', name: 'Besan Chilla', description: 'Gram-flour pancakes with onion and herbs.', timeMinutes: 20),
    ],
    'healthy': [
      CategoryDish(id: 'c-ni-h1', name: 'Moong Dal Khichdi', description: 'Mung dal and rice, light and comforting.', timeMinutes: 30),
      CategoryDish(id: 'c-ni-h2', name: 'Masoor Dal', description: 'Red lentil dal with garlic tempering.', timeMinutes: 30),
      CategoryDish(id: 'c-ni-h3', name: 'Vegetable Pulao', description: 'Light rice with garden vegetables.', timeMinutes: 35),
      CategoryDish(id: 'c-ni-h4', name: 'Mixed Veg Salad', description: 'Cucumber, tomato and onion with lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-ni-h5', name: 'Palak Paneer-light', description: 'Spinach with paneer, made light.', timeMinutes: 35),
    ],
    'dinner': [
      CategoryDish(id: 'c-ni-d1', name: 'Paneer Butter Masala', description: 'Paneer in a rich tomato-butter gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-d2', name: 'Dal Makhani', description: 'Slow-simmered black lentils with cream.', timeMinutes: 60),
      CategoryDish(id: 'c-ni-d3', name: 'Rajma Chawal', description: 'Kidney beans with steamed rice.', timeMinutes: 50),
      CategoryDish(id: 'c-ni-d4', name: 'Veg Kadai', description: 'Vegetables in a kadai masala.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-d5', name: 'Chana Masala', description: 'Chickpeas in onion-tomato masala.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-ni-v1', name: 'Paneer Butter Masala', description: 'Creamy paneer curry with naan.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-v2', name: 'Chana Masala', description: 'Spiced chickpeas with rice.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-v3', name: 'Aloo Gobhi', description: 'Cauliflower and potato with spices.', timeMinutes: 30),
      CategoryDish(id: 'c-ni-v4', name: 'Malai Kofta', description: 'Paneer dumplings in rich gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-ni-v5', name: 'Mix Veg Curry', description: 'Seasonal vegetables in a home gravy.', timeMinutes: 35),
    ],
    'nonveg': [
      CategoryDish(id: 'c-ni-n1', name: 'Butter Chicken', description: 'Chicken in a creamy tomato makhani sauce.', timeMinutes: 60),
      CategoryDish(id: 'c-ni-n2', name: 'Chicken Tikka', description: 'Char-grilled spiced chicken pieces.', timeMinutes: 45),
      CategoryDish(id: 'c-ni-n3', name: 'Mutton Rogan Josh', description: 'Rich lamb curry with aromatic spices.', timeMinutes: 90),
      CategoryDish(id: 'c-ni-n4', name: 'Fish Curry', description: 'Fish in a tangy masala gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-n5', name: 'Egg Curry', description: 'Boiled eggs in onion-tomato gravy.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-ni-s1', name: 'Gulab Jamun', description: 'Milk dumplings in rose-cardamom syrup.', timeMinutes: 45),
      CategoryDish(id: 'c-ni-s2', name: 'Gajar ka Halwa', description: 'Carrot pudding with ghee and nuts.', timeMinutes: 45),
      CategoryDish(id: 'c-ni-s3', name: 'Kheer', description: 'Rice pudding with saffron and almonds.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-s4', name: 'Rasmalai', description: 'Paneer discs in saffron milk.', timeMinutes: 45),
      CategoryDish(id: 'c-ni-s5', name: 'Sooji Halwa', description: 'Semolina halwa with ghee.', timeMinutes: 20),
    ],
    'kids': [
      CategoryDish(id: 'c-ni-k1', name: 'Veg Macaroni', description: 'Mild creamy macaroni with vegetables.', timeMinutes: 25),
      CategoryDish(id: 'c-ni-k2', name: 'Cheese Sandwich', description: 'Grilled cheese and veg sandwich.', timeMinutes: 15),
      CategoryDish(id: 'c-ni-k3', name: 'Sweet Kheer Cup', description: 'Small bowl of rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-ni-k4', name: 'Aloo Tikki', description: 'Crisp potato patties with chutney.', timeMinutes: 25),
      CategoryDish(id: 'c-ni-k5', name: 'Fruit Custard', description: 'Seasonal fruits in vanilla custard.', timeMinutes: 20),
    ],
  },
  'south_indian': {
    'breakfast': [
      CategoryDish(id: 'c-si-b1', name: 'Masala Dosa', description: 'Crisp crepe with spiced potato filling.', timeMinutes: 30),
      CategoryDish(id: 'c-si-b2', name: 'Idli Sambar', description: 'Steamed rice cakes with lentil sambar.', timeMinutes: 35),
      CategoryDish(id: 'c-si-b3', name: 'Uttapam', description: 'Thick pancake with onion and tomato.', timeMinutes: 25),
      CategoryDish(id: 'c-si-b4', name: 'Pongal', description: 'Rice and moong dal with pepper and ghee.', timeMinutes: 30),
      CategoryDish(id: 'c-si-b5', name: 'Rava Dosa', description: 'Crisp semolina crepe, lacy and thin.', timeMinutes: 25),
    ],
    'healthy': [
      CategoryDish(id: 'c-si-h1', name: 'Ragi Dosa', description: 'Finger-millet crepe, iron rich.', timeMinutes: 25),
      CategoryDish(id: 'c-si-h2', name: 'Oats Upma', description: 'Oats with vegetables and curry leaves.', timeMinutes: 20),
      CategoryDish(id: 'c-si-h3', name: 'Rasam', description: 'Tangy pepper-tomato soup.', timeMinutes: 25),
      CategoryDish(id: 'c-si-h4', name: 'Curd Rice', description: 'Rice with tempered yogurt.', timeMinutes: 15),
      CategoryDish(id: 'c-si-h5', name: 'Poriyal', description: 'Lightly spiced steamed vegetables.', timeMinutes: 25),
    ],
    'dinner': [
      CategoryDish(id: 'c-si-d1', name: 'Sambar Rice', description: 'Rice with lentil-vegetable sambar.', timeMinutes: 45),
      CategoryDish(id: 'c-si-d2', name: 'Lemon Rice', description: 'Tempered rice with lemon and peanuts.', timeMinutes: 25),
      CategoryDish(id: 'c-si-d3', name: 'Veg Biryani South', description: 'Fragrant vegetable rice with coconut.', timeMinutes: 50),
      CategoryDish(id: 'c-si-d4', name: 'Avial', description: 'Mixed vegetables in coconut-curd gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-si-d5', name: 'Tomato Rice', description: 'Rice cooked in a tangy tomato masala.', timeMinutes: 30),
    ],
    'veg': [
      CategoryDish(id: 'c-si-v1', name: 'Avial', description: 'Vegetables with coconut and curd.', timeMinutes: 40),
      CategoryDish(id: 'c-si-v2', name: 'Poriyal', description: 'Dry vegetable stir-fry with coconut.', timeMinutes: 25),
      CategoryDish(id: 'c-si-v3', name: 'Kootu', description: 'Lentil and vegetable stew.', timeMinutes: 35),
      CategoryDish(id: 'c-si-v4', name: 'Thoran', description: 'Shredded greens with grated coconut.', timeMinutes: 25),
      CategoryDish(id: 'c-si-v5', name: 'Curd Rice', description: 'Cool yogurt rice with ginger.', timeMinutes: 15),
    ],
    'nonveg': [
      CategoryDish(id: 'c-si-n1', name: 'Chettinad Chicken', description: 'Fiery chicken with black pepper and fennel.', timeMinutes: 55),
      CategoryDish(id: 'c-si-n2', name: 'Fish Fry Kerala', description: 'Crisp fish with red chilli masala.', timeMinutes: 30),
      CategoryDish(id: 'c-si-n3', name: 'Prawn Masala', description: 'Prawns in a coconut-onion masala.', timeMinutes: 40),
      CategoryDish(id: 'c-si-n4', name: 'Mutton Chukka', description: 'Dry mutton roast with curry leaves.', timeMinutes: 85),
      CategoryDish(id: 'c-si-n5', name: 'Meen Kuzhambu', description: 'Tangy fish gravy with tamarind.', timeMinutes: 45),
    ],
    'sweet': [
      CategoryDish(id: 'c-si-s1', name: 'Payasam', description: 'Rice and milk pudding with jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-si-s2', name: 'Mysore Pak', description: 'Ghee-laden gram-flour fudge.', timeMinutes: 30),
      CategoryDish(id: 'c-si-s3', name: 'Kesari', description: 'Saffron semolina halwa.', timeMinutes: 25),
      CategoryDish(id: 'c-si-s4', name: 'Adhirasam', description: 'Jaggery-rice sweet fritters.', timeMinutes: 45),
      CategoryDish(id: 'c-si-s5', name: 'Sakkarai Pongal', description: 'Sweet pongal with jaggery and ghee.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-si-k1', name: 'Mini Idli', description: 'Small steamed rice cakes with chutney.', timeMinutes: 35),
      CategoryDish(id: 'c-si-k2', name: 'Sweet Pongal Cup', description: 'Small sweet rice pudding.', timeMinutes: 30),
      CategoryDish(id: 'c-si-k3', name: 'Curd Rice Bowl', description: 'Mild yogurt rice for little ones.', timeMinutes: 15),
      CategoryDish(id: 'c-si-k4', name: 'Banana Dosa', description: 'Sweetened pancake with banana.', timeMinutes: 25),
      CategoryDish(id: 'c-si-k5', name: 'Kesari Bite', description: 'Small saffron halwa pieces.', timeMinutes: 25),
    ],
  },
  'odia': {
    'breakfast': [
      CategoryDish(id: 'c-od-b1', name: 'Chuda Ghasa', description: 'Flattened rice with coconut and jaggery.', timeMinutes: 20),
      CategoryDish(id: 'c-od-b2', name: 'Chakuli', description: 'Soft rice and chana dal crepes.', timeMinutes: 30),
      CategoryDish(id: 'c-od-b3', name: 'Poda Pitha Breakfast', description: 'Baked rice and coconut cake.', timeMinutes: 45),
      CategoryDish(id: 'c-od-b4', name: 'Khicdi', description: 'Rice and moong dal porridge.', timeMinutes: 30),
      CategoryDish(id: 'c-od-b5', name: 'Dalma Breakfast', description: 'Lentil-vegetable curry with rice.', timeMinutes: 35),
    ],
    'healthy': [
      CategoryDish(id: 'c-od-h1', name: 'Dalma', description: 'Moong dal with vegetables, light.', timeMinutes: 35),
      CategoryDish(id: 'c-od-h2', name: 'Pumpkin Sabzi', description: 'Kaddu steamed with mustard seeds.', timeMinutes: 25),
      CategoryDish(id: 'c-od-h3', name: 'Saga Bhaja', description: 'Sauteed greens, lightly done.', timeMinutes: 20),
      CategoryDish(id: 'c-od-h4', name: 'Kancha Salad', description: 'Fresh grated salad with lemon.', timeMinutes: 15),
      CategoryDish(id: 'c-od-h5', name: 'Millet Porridge', description: 'Manda pej, a cooling millet gruel.', timeMinutes: 25),
    ],
    'dinner': [
      CategoryDish(id: 'c-od-d1', name: 'Pakhala', description: 'Fermented rice with water, served cool.', timeMinutes: 30),
      CategoryDish(id: 'c-od-d2', name: 'Macha Ghanta', description: 'Fish head and lentil curry.', timeMinutes: 45),
      CategoryDish(id: 'c-od-d3', name: 'Santula', description: 'Mixed vegetable curry with dal.', timeMinutes: 35),
      CategoryDish(id: 'c-od-d4', name: 'Chingudi Jhola', description: 'Prawn curry in a light gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-od-d5', name: 'Badi Chura', description: 'Crushed lentil wafers with onion.', timeMinutes: 20),
    ],
    'veg': [
      CategoryDish(id: 'c-od-v1', name: 'Dalma', description: 'Lentils and vegetables in one pot.', timeMinutes: 35),
      CategoryDish(id: 'c-od-v2', name: 'Santula', description: 'Steamed mixed vegetables with dal.', timeMinutes: 35),
      CategoryDish(id: 'c-od-v3', name: 'Kaddu Bhaja', description: 'Crisp pumpkin fritters.', timeMinutes: 25),
      CategoryDish(id: 'c-od-v4', name: 'Saga Bhaja', description: 'Fried leafy greens.', timeMinutes: 20),
      CategoryDish(id: 'c-od-v5', name: 'Aloo Bharta', description: 'Mashed potato with mustard oil.', timeMinutes: 20),
    ],
    'nonveg': [
      CategoryDish(id: 'c-od-n1', name: 'Machha Jhola', description: 'Light fish curry with tomatoes.', timeMinutes: 40),
      CategoryDish(id: 'c-od-n2', name: 'Chicken Chaap', description: 'Rich chicken in an onion-based gravy.', timeMinutes: 60),
      CategoryDish(id: 'c-od-n3', name: 'Mutton Khasa', description: 'Slow-cooked mutton with warm spices.', timeMinutes: 85),
      CategoryDish(id: 'c-od-n4', name: 'Prawn Tawa Fry', description: 'Crisp tawa-fried prawns.', timeMinutes: 25),
      CategoryDish(id: 'c-od-n5', name: 'Egg Chop', description: 'Boiled egg in a crisp potato coat.', timeMinutes: 30),
    ],
    'sweet': [
      CategoryDish(id: 'c-od-s1', name: 'Rasagola', description: 'Spongy chhena balls in syrup.', timeMinutes: 50),
      CategoryDish(id: 'c-od-s2', name: 'Chhena Poda', description: 'Caramelised baked cheese dessert.', timeMinutes: 60),
      CategoryDish(id: 'c-od-s3', name: 'Kheer', description: 'Rice pudding with cardamom.', timeMinutes: 40),
      CategoryDish(id: 'c-od-s4', name: 'Poda Pitha', description: 'Baked coconut-rice cake.', timeMinutes: 45),
      CategoryDish(id: 'c-od-s5', name: 'Rasabali', description: 'Fried chhena in sweet milk.', timeMinutes: 50),
    ],
    'kids': [
      CategoryDish(id: 'c-od-k1', name: 'Sweet Chuda', description: 'Flattened rice with jaggery and coconut.', timeMinutes: 20),
      CategoryDish(id: 'c-od-k2', name: 'Mini Chakuli', description: 'Small soft rice crepes.', timeMinutes: 30),
      CategoryDish(id: 'c-od-k3', name: 'Rasagola', description: 'A soft sweet ball kids adore.', timeMinutes: 50),
      CategoryDish(id: 'c-od-k4', name: 'Banana Pitha', description: 'Sweet banana rice cake.', timeMinutes: 30),
      CategoryDish(id: 'c-od-k5', name: 'Khicdi Bowl', description: 'Mild rice-lentil porridge.', timeMinutes: 30),
    ],
  },
  'bengali': {
    'breakfast': [
      CategoryDish(id: 'c-be-b1', name: 'Luchi Aloo', description: 'Puffed fried bread with spiced potato.', timeMinutes: 35),
      CategoryDish(id: 'c-be-b2', name: 'Aloo Paratha Bengali', description: 'Paratha with a potato-peas filling.', timeMinutes: 35),
      CategoryDish(id: 'c-be-b3', name: 'Muri with Cholar Dal', description: 'Puffed rice with sweet chana dal.', timeMinutes: 30),
      CategoryDish(id: 'c-be-b4', name: 'Panta Bhaat', description: 'Soaked rice with mustard oil and chilli.', timeMinutes: 15),
      CategoryDish(id: 'c-be-b5', name: 'Koraishutir Kochuri', description: 'Green pea stuffed fried bread.', timeMinutes: 40),
    ],
    'healthy': [
      CategoryDish(id: 'c-be-h1', name: 'Moong Dal Bengali', description: 'Yellow dal with panch phoron.', timeMinutes: 30),
      CategoryDish(id: 'c-be-h2', name: 'Shukto', description: 'Bitter-sweet vegetable stew.', timeMinutes: 35),
      CategoryDish(id: 'c-be-h3', name: 'Pumpkin Sabzi', description: 'Kumro steamed with mustard seeds.', timeMinutes: 25),
      CategoryDish(id: 'c-be-h4', name: 'Saag Bhaja', description: 'Greens sauteed with garlic.', timeMinutes: 20),
      CategoryDish(id: 'c-be-h5', name: 'Beet Raita', description: 'Grated beet in yogurt.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-be-d1', name: 'Macher Jhol', description: 'Light fish curry with mustard and spices.', timeMinutes: 40),
      CategoryDish(id: 'c-be-d2', name: 'Cholar Dal', description: 'Bengal gram dal with coconut and ghee.', timeMinutes: 35),
      CategoryDish(id: 'c-be-d3', name: 'Aloo Posto', description: 'Potato with poppy-seed paste.', timeMinutes: 30),
      CategoryDish(id: 'c-be-d4', name: 'Chingri Malai', description: 'Prawns in coconut milk.', timeMinutes: 40),
      CategoryDish(id: 'c-be-d5', name: 'Doi Maach', description: 'Fish in a yogurt gravy.', timeMinutes: 40),
    ],
    'veg': [
      CategoryDish(id: 'c-be-v1', name: 'Shukto', description: 'Mixed bitter vegetable stew.', timeMinutes: 35),
      CategoryDish(id: 'c-be-v2', name: 'Aloo Posto', description: 'Potatoes with poppy seed paste.', timeMinutes: 30),
      CategoryDish(id: 'c-be-v3', name: 'Jhuri Aloo Bhaja', description: 'Crisp fried potato straws.', timeMinutes: 25),
      CategoryDish(id: 'c-be-v4', name: 'Chorchori', description: 'Mixed vegetable medley.', timeMinutes: 30),
      CategoryDish(id: 'c-be-v5', name: 'Mocha Ghonto', description: 'Banana flower curry with spices.', timeMinutes: 45),
    ],
    'nonveg': [
      CategoryDish(id: 'c-be-n1', name: 'Macher Jhol', description: 'Mustard fish curry, light and tangy.', timeMinutes: 40),
      CategoryDish(id: 'c-be-n2', name: 'Chingri Malai Curry', description: 'Prawns in creamy coconut gravy.', timeMinutes: 40),
      CategoryDish(id: 'c-be-n3', name: 'Kosha Mangsho', description: 'Slow-cooked mutton with caramelised onions.', timeMinutes: 90),
      CategoryDish(id: 'c-be-n4', name: 'Fish Paturi', description: 'Mustard fish steamed in a leaf.', timeMinutes: 35),
      CategoryDish(id: 'c-be-n5', name: 'Chicken Rezala', description: 'Mild chicken in a white sauce.', timeMinutes: 55),
    ],
    'sweet': [
      CategoryDish(id: 'c-be-s1', name: 'Rosogolla', description: 'Soft chhena balls in syrup.', timeMinutes: 50),
      CategoryDish(id: 'c-be-s2', name: 'Mishti Doi', description: 'Caramelised jaggery yogurt.', timeMinutes: 40),
      CategoryDish(id: 'c-be-s3', name: 'Sandesh', description: 'Fresh chhena sweet with cardamom.', timeMinutes: 30),
      CategoryDish(id: 'c-be-s4', name: 'Chomchom', description: 'Syrupy chhena sweet with coconut.', timeMinutes: 45),
      CategoryDish(id: 'c-be-s5', name: 'Payesh', description: 'Rice pudding with jaggery.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-be-k1', name: 'Mini Kochuri', description: 'Small puffed breads with pea filling.', timeMinutes: 40),
      CategoryDish(id: 'c-be-k2', name: 'Rosogolla', description: 'A soft, sweet chhena ball.', timeMinutes: 50),
      CategoryDish(id: 'c-be-k3', name: 'Sweet Doi', description: 'Yogurt sweetened with jaggery.', timeMinutes: 40),
      CategoryDish(id: 'c-be-k4', name: 'Muri Chaat', description: 'Puffed rice with peanuts and lemon.', timeMinutes: 10),
      CategoryDish(id: 'c-be-k5', name: 'Banana Payesh', description: 'Mild banana rice pudding.', timeMinutes: 35),
    ],
  },
  'awadhi': {
    'breakfast': [
      CategoryDish(id: 'c-aw-b1', name: 'Nihari Kulcha', description: 'Slow-cooked stew with soft bread.', timeMinutes: 60),
      CategoryDish(id: 'c-aw-b2', name: 'Sheermal', description: 'Saffron-scented sweet flatbread.', timeMinutes: 45),
      CategoryDish(id: 'c-aw-b3', name: 'Lukhnawi Anda Toast', description: 'Spiced egg toast from the old city.', timeMinutes: 15),
      CategoryDish(id: 'c-aw-b4', name: 'Khasta Roti', description: 'Crisp layered flatbread with chai.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-b5', name: 'Malai Toast', description: 'Sweet cream-topped toast.', timeMinutes: 15),
    ],
    'healthy': [
      CategoryDish(id: 'c-aw-h1', name: 'Moong Dal Awadhi', description: 'Light yellow dal with ghee.', timeMinutes: 30),
      CategoryDish(id: 'c-aw-h2', name: 'Kaddu Ka Bharta', description: 'Roasted pumpkin mash.', timeMinutes: 30),
      CategoryDish(id: 'c-aw-h3', name: 'Bhindi Awadhi', description: 'Okra cooked with mild spices.', timeMinutes: 25),
      CategoryDish(id: 'c-aw-h4', name: 'Vegetable Yakhni', description: 'Light vegetable stew with cardamom.', timeMinutes: 35),
      CategoryDish(id: 'c-aw-h5', name: 'Mint Raita Bowl', description: 'Cooling yogurt with mint and boondi.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-aw-d1', name: 'Awadhi Biryani', description: 'Slow-cooked saffron rice with meat.', timeMinutes: 70),
      CategoryDish(id: 'c-aw-d2', name: 'Galouti Kebab', description: 'Melt-in-the-mouth minced patties.', timeMinutes: 60),
      CategoryDish(id: 'c-aw-d3', name: 'Nihari', description: 'Overnight-cooked meat stew.', timeMinutes: 90),
      CategoryDish(id: 'c-aw-d4', name: 'Shahi Paneer', description: 'Paneer in a saffron-almond gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-aw-d5', name: 'Murg Musallam', description: 'Whole chicken in a rich masala.', timeMinutes: 90),
    ],
    'veg': [
      CategoryDish(id: 'c-aw-v1', name: 'Shahi Paneer', description: 'Rich royal paneer curry.', timeMinutes: 45),
      CategoryDish(id: 'c-aw-v2', name: 'Nargisi Kofta Veg', description: 'Veg koftas in a smooth gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-aw-v3', name: 'Dum Aloo Awadhi', description: 'Baby potatoes slow-cooked.', timeMinutes: 45),
      CategoryDish(id: 'c-aw-v4', name: 'Kaddu Ka Kofta', description: 'Pumpkin dumplings in tomato gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-aw-v5', name: 'Malai Bhindi', description: 'Okra in a cream gravy.', timeMinutes: 30),
    ],
    'nonveg': [
      CategoryDish(id: 'c-aw-n1', name: 'Galouti Kebab', description: 'Velvety minced meat kebabs.', timeMinutes: 60),
      CategoryDish(id: 'c-aw-n2', name: 'Nihari', description: 'Rich slow-braised meat stew.', timeMinutes: 90),
      CategoryDish(id: 'c-aw-n3', name: 'Murg Musallam', description: 'Spiced whole chicken, royal style.', timeMinutes: 90),
      CategoryDish(id: 'c-aw-n4', name: 'Kakori Kebab', description: 'Minced kebab on a skewer.', timeMinutes: 55),
      CategoryDish(id: 'c-aw-n5', name: 'Chicken Rezala Awadhi', description: 'Mild, fragrant white chicken curry.', timeMinutes: 55),
    ],
    'sweet': [
      CategoryDish(id: 'c-aw-s1', name: 'Shahi Tukda', description: 'Fried bread in saffron milk.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-s2', name: 'Kheer', description: 'Saffron rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-s3', name: 'Matthi', description: 'Sweet fried flour biscuits.', timeMinutes: 35),
      CategoryDish(id: 'c-aw-s4', name: 'Phirni', description: 'Ground rice pudding in bowls.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-s5', name: 'Baqarkhani Sweet', description: 'Sweet saffron flatbread.', timeMinutes: 40),
    ],
    'kids': [
      CategoryDish(id: 'c-aw-k1', name: 'Malai Toast', description: 'Sweet creamy toast.', timeMinutes: 15),
      CategoryDish(id: 'c-aw-k2', name: 'Mini Sheermal', description: 'Small saffron sweet bread.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-k3', name: 'Shahi Tukda Bite', description: 'Small bread pudding squares.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-k4', name: 'Kheer Cup', description: 'Sweet rice pudding cup.', timeMinutes: 40),
      CategoryDish(id: 'c-aw-k5', name: 'Egg Toast', description: 'Mild spiced egg toast.', timeMinutes: 15),
    ],
  },
  'muglai': {
    'breakfast': [
      CategoryDish(id: 'c-mg-b1', name: 'Sheermal', description: 'Sweet saffron flatbread.', timeMinutes: 45),
      CategoryDish(id: 'c-mg-b2', name: 'Kulcha Nihari', description: 'Soft bread with slow stew.', timeMinutes: 60),
      CategoryDish(id: 'c-mg-b3', name: 'Anda Paratha', description: 'Egg-stuffed flatbread.', timeMinutes: 25),
      CategoryDish(id: 'c-mg-b4', name: 'Malai Toast', description: 'Cream-topped sweet toast.', timeMinutes: 15),
      CategoryDish(id: 'c-mg-b5', name: 'Shami Breakfast', description: 'Spiced minced patties with bread.', timeMinutes: 40),
    ],
    'healthy': [
      CategoryDish(id: 'c-mg-h1', name: 'Moong Dal Muglai', description: 'Light dal with whole spices.', timeMinutes: 30),
      CategoryDish(id: 'c-mg-h2', name: 'Lauki Pulao', description: 'Bottle gourd rice, mild and light.', timeMinutes: 35),
      CategoryDish(id: 'c-mg-h3', name: 'Veg Yakhni', description: 'Vegetable stew with saffron.', timeMinutes: 35),
      CategoryDish(id: 'c-mg-h4', name: 'Raita Muglai', description: 'Boondi raita with roasted cumin.', timeMinutes: 15),
      CategoryDish(id: 'c-mg-h5', name: 'Grilled Corn Masala', description: 'Charred corn with lemon and spice.', timeMinutes: 15),
    ],
    'dinner': [
      CategoryDish(id: 'c-mg-d1', name: 'Mughlai Biryani', description: 'Rich layered rice with saffron and nuts.', timeMinutes: 70),
      CategoryDish(id: 'c-mg-d2', name: 'Murgh Korma', description: 'Chicken in a cashew-yogurt gravy.', timeMinutes: 60),
      CategoryDish(id: 'c-mg-d3', name: 'Shami Kebab', description: 'Spiced minced lamb patties.', timeMinutes: 50),
      CategoryDish(id: 'c-mg-d4', name: 'Mughlai Paneer', description: 'Paneer in a rich almond gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-mg-d5', name: 'Nihari', description: 'Slow-cooked rich meat stew.', timeMinutes: 90),
    ],
    'veg': [
      CategoryDish(id: 'c-mg-v1', name: 'Mughlai Paneer', description: 'Paneer in royal almond gravy.', timeMinutes: 45),
      CategoryDish(id: 'c-mg-v2', name: 'Veg Kofta', description: 'Vegetable dumplings in creamy gravy.', timeMinutes: 50),
      CategoryDish(id: 'c-mg-v3', name: 'Dum Aloo', description: 'Slow-cooked baby potatoes.', timeMinutes: 45),
      CategoryDish(id: 'c-mg-v4', name: 'Matar Paneer Muglai', description: 'Peas and paneer in a mild curry.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-v5', name: 'Gobi Musallam', description: 'Whole cauliflower in spiced gravy.', timeMinutes: 55),
    ],
    'nonveg': [
      CategoryDish(id: 'c-mg-n1', name: 'Murgh Korma', description: 'Rich chicken korma with saffron.', timeMinutes: 60),
      CategoryDish(id: 'c-mg-n2', name: 'Shami Kebab', description: 'Succulent minced lamb patties.', timeMinutes: 50),
      CategoryDish(id: 'c-mg-n3', name: 'Mutton Korma', description: 'Mutton in a smooth royal gravy.', timeMinutes: 90),
      CategoryDish(id: 'c-mg-n4', name: 'Nihari', description: 'Rich slow-braised stew.', timeMinutes: 90),
      CategoryDish(id: 'c-mg-n5', name: 'Fish Tikka Muglai', description: 'Marinated fish, charcoal-grilled.', timeMinutes: 40),
    ],
    'sweet': [
      CategoryDish(id: 'c-mg-s1', name: 'Shahi Tukda', description: 'Saffron-soaked bread pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-s2', name: 'Phirni', description: 'Chilled ground rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-s3', name: 'Kheer', description: 'Rich milk pudding with nuts.', timeMinutes: 45),
      CategoryDish(id: 'c-mg-s4', name: 'Matthi', description: 'Sweet fried biscuits.', timeMinutes: 35),
      CategoryDish(id: 'c-mg-s5', name: 'Falooda', description: 'Iced dessert with noodles and basil.', timeMinutes: 30),
    ],
    'kids': [
      CategoryDish(id: 'c-mg-k1', name: 'Malai Toast', description: 'Sweet cream toast.', timeMinutes: 15),
      CategoryDish(id: 'c-mg-k2', name: 'Shami Bite', description: 'Small mild kebab patties.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-k3', name: 'Phirni Cup', description: 'Small chilled rice pudding.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-k4', name: 'Sweet Sheermal', description: 'Sweet bread, warm and soft.', timeMinutes: 40),
      CategoryDish(id: 'c-mg-k5', name: 'Kheer Bowl', description: 'Comforting rice pudding.', timeMinutes: 40),
    ],
  },
};
